table dim_customer
	lineageTag: 1ace2605-f91c-4dba-a17c-16b7d1afa4b1

	column customer_id
		dataType: int64
		formatString: 0
		lineageTag: 2f58fa72-11f2-402b-89ee-aa2a92957236
		summarizeBy: none
		sourceColumn: customer_id

		annotation SummarizationSetBy = Automatic

	column full_name
		dataType: string
		lineageTag: a09e3943-fa6c-48ae-a3d8-e7c65fae3489
		summarizeBy: none
		sourceColumn: full_name

		annotation SummarizationSetBy = Automatic

	column email
		dataType: string
		lineageTag: a277e9fe-4ee8-4ff4-aeb1-b1e962b489be
		summarizeBy: none
		sourceColumn: email

		annotation SummarizationSetBy = Automatic

	column state
		dataType: string
		lineageTag: 04e38c9c-5e93-41bb-a5a4-94c03b0d2d34
		summarizeBy: none
		sourceColumn: state

		annotation SummarizationSetBy = Automatic

	column customer_segment
		dataType: string
		lineageTag: bb0e6212-70b5-4b06-a4c0-99436feeeaa7
		summarizeBy: none
		sourceColumn: customer_segment

		annotation SummarizationSetBy = Automatic

	partition dim_customer = m
		mode: import
		source = ```
				let
				    // 1. Execute the Python script and inject your parameters safely with explicit Int64 types
				    Source = Python.Execute("import sqlite3#(lf)import pandas as pd#(lf)import matplotlib as mpl#(lf)#(lf)conn = sqlite3.connect(""C:\Github\sql-practice\project\oakhaven.db"")#(lf)df = pd.read_sql_query(""""""#(lf)SELECT DISTINCT #(lf)    c.customer_id,#(lf)    c.full_name,#(lf)    c.email,#(lf)    c.state,#(lf)    c.customer_segment#(lf)FROM dim_customer c#(lf)WHERE c.customer_id IN (#(lf)    SELECT customer_id #(lf)    FROM fact_sales #(lf)    ORDER BY order_date DESC, order_id, order_line_id #(lf)    LIMIT 100#(lf));#(lf)"""""", conn, dtype={'customer_id': 'Int64'})#(lf)conn.close()"),
				    
				    // 2. Extract the dataframe 'df' that Python generated
				    DataTable = Source{[Name="df"]}[Value],
				    
				    // 3. Transform column data types
				    #"Changed Type" = Table.TransformColumnTypes(DataTable,{
				        {"customer_id", Int64.Type},
				        {"full_name", type text},
				        {"email", type text},
				        {"state", type text},
				        {"customer_segment", type text}
				    })
				in
				    #"Changed Type"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

