-- =============================================================================
-- AUTOMATICALLY GENERATED DDL & METADATA CATALOG FROM POWER BI TMDL & M METADATA
-- Generated by: pbip_poc/tools/parse_tmdl.py
-- =============================================================================

DROP TABLE IF EXISTS _tmdl_projects;
DROP TABLE IF EXISTS _tmdl_tables;
DROP TABLE IF EXISTS _tmdl_columns;
DROP TABLE IF EXISTS _tmdl_measures;
DROP TABLE IF EXISTS _tmdl_relationships;
DROP TABLE IF EXISTS _tmdl_data_sources;
DROP TABLE IF EXISTS _tmdl_m_steps;
DROP TABLE IF EXISTS _tmdl_parameters;
CREATE TABLE IF NOT EXISTS _tmdl_projects (project_name TEXT PRIMARY KEY, table_count INT, relationship_count INT, parameter_count INT);
CREATE TABLE IF NOT EXISTS _tmdl_tables (project_name TEXT, table_name TEXT, lineage_tag TEXT, PRIMARY KEY (project_name, table_name));
CREATE TABLE IF NOT EXISTS _tmdl_columns (project_name TEXT, table_name TEXT, column_name TEXT, data_type TEXT, summarize_by TEXT, source_column TEXT, description TEXT);
CREATE TABLE IF NOT EXISTS _tmdl_measures (project_name TEXT, table_name TEXT, measure_name TEXT, expression TEXT, format_string TEXT, description TEXT);
CREATE TABLE IF NOT EXISTS _tmdl_relationships (project_name TEXT, rel_name TEXT, from_table TEXT, from_column TEXT, to_table TEXT, to_column TEXT, cardinality TEXT);
CREATE TABLE IF NOT EXISTS _tmdl_data_sources (project_name TEXT, table_name TEXT, connector TEXT, connection_target TEXT, query_type TEXT);
CREATE TABLE IF NOT EXISTS _tmdl_m_steps (project_name TEXT, table_name TEXT, step_index INT, step_name TEXT, step_type TEXT, code_snippet TEXT);
CREATE TABLE IF NOT EXISTS _tmdl_parameters (project_name TEXT, param_name TEXT, data_type TEXT, default_value TEXT);

-- PROJECT: duplicated oakhaven template
INSERT OR REPLACE INTO _tmdl_projects VALUES ('duplicated oakhaven template', 13, 5, 1);
INSERT INTO _tmdl_parameters VALUES ('duplicated oakhaven template', 'oakhavendatabasepath', 'Text', 'project/oakhaven.db');
INSERT INTO _tmdl_relationships VALUES ('duplicated oakhaven template', 'AutoDetected_1d28b393-7c5a-472e-8bdf-bbaefdfadc47', 'fact_sales', 'customer_id', 'dim_customer', 'customer_id', 'one');
INSERT INTO _tmdl_relationships VALUES ('duplicated oakhaven template', 'AutoDetected_de8de45f-ebb1-4d1d-a6b4-e19e17d854ac', 'fact_sales', 'datekey', 'dim_calendar', 'datekey', 'one');
INSERT INTO _tmdl_relationships VALUES ('duplicated oakhaven template', 'cdcabb57-8502-4d1c-1ca6-c29df34d8d3e', 'fact_sales', 'employee_id', 'dim_employee', 'employee_id', 'one');
INSERT INTO _tmdl_relationships VALUES ('duplicated oakhaven template', 'dab805ef-d296-87a4-acb2-347f07dc4199', 'flat_sales_all', 'order_date', 'dim_calendar', 'date', 'one');
INSERT INTO _tmdl_relationships VALUES ('duplicated oakhaven template', 'defc8ca4-33ee-19ab-d42b-240fcd45be3e', 'flat_sales_completed', 'order_date', 'dim_calendar', 'date', 'one');
INSERT OR REPLACE INTO _tmdl_tables VALUES ('duplicated oakhaven template', 'dim_calendar', 'None');
INSERT INTO _tmdl_data_sources VALUES ('duplicated oakhaven template', 'dim_calendar', 'SQLite (Python Connector)', '"project/oakhaven.db"', 'Native SQL Pushdown');
INSERT INTO _tmdl_m_steps VALUES ('duplicated oakhaven template', 'dim_calendar', 1, 'Source', 'Source Ingestion', 'Python.Execute("import sqlite3
import pandas as pd
import matplotlib as mpl

conn = sqlite3.connect(...');
INSERT INTO _tmdl_columns VALUES ('duplicated oakhaven template', 'dim_calendar', 'datekey', 'string', 'none', 'datekey', 'Integer surrogate key in YYYYMMDD format for date joins.');
INSERT INTO _tmdl_columns VALUES ('duplicated oakhaven template', 'dim_calendar', 'date', 'string', 'none', 'date', 'Standard ISO 8601 calendar date (YYYY-MM-DD).');
INSERT INTO _tmdl_columns VALUES ('duplicated oakhaven template', 'dim_calendar', 'year', 'string', 'none', 'year', 'Four-digit calendar year (e.g. 2026).');
INSERT INTO _tmdl_columns VALUES ('duplicated oakhaven template', 'dim_calendar', 'month', 'string', 'none', 'month', 'Numeric calendar month (1..12).');
INSERT INTO _tmdl_columns VALUES ('duplicated oakhaven template', 'dim_calendar', 'month_name', 'string', 'none', 'month_name', 'Full English month name (e.g. January, February).');
INSERT INTO _tmdl_columns VALUES ('duplicated oakhaven template', 'dim_calendar', 'quarter', 'string', 'none', 'quarter', 'Calendar quarter identifier (Q1, Q2, Q3, Q4).');
INSERT INTO _tmdl_columns VALUES ('duplicated oakhaven template', 'dim_calendar', 'day_name', 'string', 'none', 'day_name', 'Full English day name (e.g. Monday, Tuesday).');
INSERT INTO _tmdl_columns VALUES ('duplicated oakhaven template', 'dim_calendar', 'is_weekend', 'string', 'none', 'is_weekend', 'Boolean flag indicating Saturday or Sunday (1 = Weekend, 0 = Weekday).');
CREATE TABLE IF NOT EXISTS tmdl_duplicated_oakhaven_template_dim_calendar (
    datekey TEXT,
    date TEXT,
    year TEXT,
    month TEXT,
    month_name TEXT,
    quarter TEXT,
    day_name TEXT,
    is_weekend TEXT
);

INSERT OR REPLACE INTO _tmdl_tables VALUES ('duplicated oakhaven template', 'dim_customer', 'None');
INSERT INTO _tmdl_data_sources VALUES ('duplicated oakhaven template', 'dim_customer', 'SQLite (Python Connector)', '"project/oakhaven.db"', 'Native SQL Pushdown');
INSERT INTO _tmdl_m_steps VALUES ('duplicated oakhaven template', 'dim_customer', 1, 'Source', 'Source Ingestion', 'Python.Execute("import sqlite3
import pandas as pd
import matplotlib as mpl

conn = sqlite3.connect(...');
INSERT INTO _tmdl_columns VALUES ('duplicated oakhaven template', 'dim_customer', 'customer_id', 'string', 'none', 'customer_id', 'Unique sequential identifier (1..600) for each customer.');
INSERT INTO _tmdl_columns VALUES ('duplicated oakhaven template', 'dim_customer', 'full_name', 'string', 'none', 'full_name', 'Concatenated customer full name (first + last).');
INSERT INTO _tmdl_columns VALUES ('duplicated oakhaven template', 'dim_customer', 'email', 'string', 'none', 'email', 'Primary email address associated with customer account.');
INSERT INTO _tmdl_columns VALUES ('duplicated oakhaven template', 'dim_customer', 'state', 'string', 'none', 'state', 'Customer geographic state or province code.');
INSERT INTO _tmdl_columns VALUES ('duplicated oakhaven template', 'dim_customer', 'customer_segment', 'string', 'none', 'customer_segment', 'Market segment classification (Retail, Wholesale, VIP).');
CREATE TABLE IF NOT EXISTS tmdl_duplicated_oakhaven_template_dim_customer (
    customer_id TEXT,
    full_name TEXT,
    email TEXT,
    state TEXT,
    customer_segment TEXT
);

INSERT OR REPLACE INTO _tmdl_tables VALUES ('duplicated oakhaven template', 'dim_employee', 'None');
INSERT INTO _tmdl_data_sources VALUES ('duplicated oakhaven template', 'dim_employee', 'SQLite (Python Connector)', '"project/oakhaven.db"', 'Native SQL Pushdown');
INSERT INTO _tmdl_m_steps VALUES ('duplicated oakhaven template', 'dim_employee', 1, 'Source', 'Source Ingestion', 'Python.Execute("import sqlite3
import pandas as pd
import matplotlib as mpl

conn = sqlite3.connect(...');
INSERT INTO _tmdl_columns VALUES ('duplicated oakhaven template', 'dim_employee', 'employee_id', 'string', 'none', 'employee_id', 'Unique employee identification number (1..35).');
INSERT INTO _tmdl_columns VALUES ('duplicated oakhaven template', 'dim_employee', 'full_name', 'string', 'none', 'full_name', 'Concatenated customer full name (first + last).');
INSERT INTO _tmdl_columns VALUES ('duplicated oakhaven template', 'dim_employee', 'department', 'string', 'none', 'department', 'Company department (Sales, Support, Warehouse, Management).');
INSERT INTO _tmdl_columns VALUES ('duplicated oakhaven template', 'dim_employee', 'region', 'string', 'none', 'region', 'Assigned geographical sales territory (West, East, Central, South).');
CREATE TABLE IF NOT EXISTS tmdl_duplicated_oakhaven_template_dim_employee (
    employee_id TEXT,
    full_name TEXT,
    department TEXT,
    region TEXT
);

INSERT OR REPLACE INTO _tmdl_tables VALUES ('duplicated oakhaven template', 'fact_sales', 'None');
INSERT INTO _tmdl_data_sources VALUES ('duplicated oakhaven template', 'fact_sales', 'SQLite (Python Connector)', '"project/oakhaven.db"', 'Native SQL Pushdown');
INSERT INTO _tmdl_m_steps VALUES ('duplicated oakhaven template', 'fact_sales', 1, 'Source', 'Source Ingestion', 'Python.Execute("import sqlite3
import pandas as pd
import matplotlib as mpl

conn = sqlite3.connect(...');
INSERT INTO _tmdl_m_steps VALUES ('duplicated oakhaven template', 'fact_sales', 2, 'DataTable', 'Source Ingestion', 'Source{[Name="df"]}[Value]');
INSERT INTO _tmdl_columns VALUES ('duplicated oakhaven template', 'fact_sales', 'order_id', 'string', 'none', 'order_id', 'Unique sales order transaction header identifier.');
INSERT INTO _tmdl_columns VALUES ('duplicated oakhaven template', 'fact_sales', 'order_line_id', 'string', 'none', 'order_line_id', 'Line item sequence number (1..N) within an order.');
INSERT INTO _tmdl_columns VALUES ('duplicated oakhaven template', 'fact_sales', 'customer_id', 'string', 'none', 'customer_id', 'Unique sequential identifier (1..600) for each customer.');
INSERT INTO _tmdl_columns VALUES ('duplicated oakhaven template', 'fact_sales', 'product_id', 'string', 'none', 'product_id', 'Unique surrogate key (1..150) identifying each merchandise item.');
INSERT INTO _tmdl_columns VALUES ('duplicated oakhaven template', 'fact_sales', 'employee_id', 'string', 'none', 'employee_id', 'Unique employee identification number (1..35).');
INSERT INTO _tmdl_columns VALUES ('duplicated oakhaven template', 'fact_sales', 'datekey', 'string', 'none', 'datekey', 'Integer surrogate key in YYYYMMDD format for date joins.');
INSERT INTO _tmdl_columns VALUES ('duplicated oakhaven template', 'fact_sales', 'quantity', 'string', 'none', 'quantity', 'Number of units purchased in order line.');
INSERT INTO _tmdl_columns VALUES ('duplicated oakhaven template', 'fact_sales', 'unit_price', 'string', 'none', 'unit_price', 'Retail selling price per unit ($) at time of order.');
INSERT INTO _tmdl_columns VALUES ('duplicated oakhaven template', 'fact_sales', 'discount_pct', 'string', 'none', 'discount_pct', 'Percentage discount applied (0.00 to 0.30).');
INSERT INTO _tmdl_columns VALUES ('duplicated oakhaven template', 'fact_sales', 'net_amount', 'string', 'none', 'net_amount', 'Actual net revenue earned after applying discounts.');
INSERT INTO _tmdl_columns VALUES ('duplicated oakhaven template', 'fact_sales', 'payment_method', 'string', 'none', 'payment_method', 'Payment tender channel (Credit Card, PayPal, Cash, Debit Card).');
INSERT INTO _tmdl_columns VALUES ('duplicated oakhaven template', 'fact_sales', 'order_status', 'string', 'none', 'order_status', 'Current status of transaction (Completed, Processing, Canceled, Returned).');
INSERT INTO _tmdl_columns VALUES ('duplicated oakhaven template', 'fact_sales', 'channel', 'string', 'none', 'channel', 'Sales channel origination (Web, Mobile App, In-Store Retail).');
CREATE TABLE IF NOT EXISTS tmdl_duplicated_oakhaven_template_fact_sales (
    order_id TEXT,
    order_line_id TEXT,
    customer_id TEXT,
    product_id TEXT,
    employee_id TEXT,
    datekey TEXT,
    quantity TEXT,
    unit_price TEXT,
    discount_pct TEXT,
    net_amount TEXT,
    payment_method TEXT,
    order_status TEXT,
    channel TEXT,
    FOREIGN KEY (customer_id) REFERENCES tmdl_duplicated_oakhaven_template_dim_customer(customer_id),
    FOREIGN KEY (datekey) REFERENCES tmdl_duplicated_oakhaven_template_dim_calendar(datekey),
    FOREIGN KEY (employee_id) REFERENCES tmdl_duplicated_oakhaven_template_dim_employee(employee_id)
);

INSERT OR REPLACE INTO _tmdl_tables VALUES ('duplicated oakhaven template', 'flat_sales_all', 'None');
INSERT INTO _tmdl_data_sources VALUES ('duplicated oakhaven template', 'flat_sales_all', 'SQLite (Python Connector)', '"project/oakhaven.db"', 'Native SQL Pushdown');
INSERT INTO _tmdl_m_steps VALUES ('duplicated oakhaven template', 'flat_sales_all', 1, 'Source', 'Source Ingestion', 'Python.Execute("import sqlite3
import pandas as pd
import matplotlib as mpl

conn = sqlite3.connect(...');
INSERT INTO _tmdl_m_steps VALUES ('duplicated oakhaven template', 'flat_sales_all', 2, 'DataTable', 'Source Ingestion', 'Source{[Name="df"]}[Value]');
INSERT INTO _tmdl_columns VALUES ('duplicated oakhaven template', 'flat_sales_all', 'order_id', 'string', 'none', 'order_id', 'Unique sales order transaction header identifier.');
INSERT INTO _tmdl_columns VALUES ('duplicated oakhaven template', 'flat_sales_all', 'order_line_id', 'string', 'none', 'order_line_id', 'Line item sequence number (1..N) within an order.');
INSERT INTO _tmdl_columns VALUES ('duplicated oakhaven template', 'flat_sales_all', 'order_date', 'string', 'none', 'order_date', 'Transaction date on which order was placed.');
INSERT INTO _tmdl_columns VALUES ('duplicated oakhaven template', 'flat_sales_all', 'customer_name', 'string', 'none', 'customer_name', 'Full name of the purchasing customer.');
INSERT INTO _tmdl_columns VALUES ('duplicated oakhaven template', 'flat_sales_all', 'product_name', 'string', 'none', 'product_name', 'Catalog description and product title.');
INSERT INTO _tmdl_columns VALUES ('duplicated oakhaven template', 'flat_sales_all', 'product_category', 'string', 'none', 'product_category', 'Merchandise category of the ordered item.');
INSERT INTO _tmdl_columns VALUES ('duplicated oakhaven template', 'flat_sales_all', 'quantity', 'string', 'none', 'quantity', 'Number of units purchased in order line.');
INSERT INTO _tmdl_columns VALUES ('duplicated oakhaven template', 'flat_sales_all', 'net_amount', 'string', 'none', 'net_amount', 'Actual net revenue earned after applying discounts.');
INSERT INTO _tmdl_columns VALUES ('duplicated oakhaven template', 'flat_sales_all', 'channel', 'string', 'none', 'channel', 'Sales channel origination (Web, Mobile App, In-Store Retail).');
CREATE TABLE IF NOT EXISTS tmdl_duplicated_oakhaven_template_flat_sales_all (
    order_id TEXT,
    order_line_id TEXT,
    order_date TEXT,
    customer_name TEXT,
    product_name TEXT,
    product_category TEXT,
    quantity TEXT,
    net_amount TEXT,
    channel TEXT,
    FOREIGN KEY (order_date) REFERENCES tmdl_duplicated_oakhaven_template_dim_calendar(date)
);

INSERT OR REPLACE INTO _tmdl_tables VALUES ('duplicated oakhaven template', 'flat_sales_completed', 'None');
INSERT INTO _tmdl_data_sources VALUES ('duplicated oakhaven template', 'flat_sales_completed', 'SQLite (Python Connector)', '"project/oakhaven.db"', 'Native SQL Pushdown');
INSERT INTO _tmdl_m_steps VALUES ('duplicated oakhaven template', 'flat_sales_completed', 1, 'Source', 'Source Ingestion', 'Python.Execute("import sqlite3
import pandas as pd
import matplotlib as mpl

conn = sqlite3.connect(...');
INSERT INTO _tmdl_m_steps VALUES ('duplicated oakhaven template', 'flat_sales_completed', 2, 'customer_id', 'Filter Transformation', 'c.customer_id
LEFT JOIN dim_product p ON f.product_id = p.product_id
WHERE f.order_status = ''Complet...');
INSERT INTO _tmdl_m_steps VALUES ('duplicated oakhaven template', 'flat_sales_completed', 3, 'DataTable', 'Source Ingestion', 'Source{[Name="df"]}[Value]');
INSERT INTO _tmdl_columns VALUES ('duplicated oakhaven template', 'flat_sales_completed', 'order_id', 'string', 'none', 'order_id', 'Unique sales order transaction header identifier.');
INSERT INTO _tmdl_columns VALUES ('duplicated oakhaven template', 'flat_sales_completed', 'order_line_id', 'string', 'none', 'order_line_id', 'Line item sequence number (1..N) within an order.');
INSERT INTO _tmdl_columns VALUES ('duplicated oakhaven template', 'flat_sales_completed', 'order_date', 'string', 'none', 'order_date', 'Transaction date on which order was placed.');
INSERT INTO _tmdl_columns VALUES ('duplicated oakhaven template', 'flat_sales_completed', 'customer_name', 'string', 'none', 'customer_name', 'Full name of the purchasing customer.');
INSERT INTO _tmdl_columns VALUES ('duplicated oakhaven template', 'flat_sales_completed', 'product_name', 'string', 'none', 'product_name', 'Catalog description and product title.');
INSERT INTO _tmdl_columns VALUES ('duplicated oakhaven template', 'flat_sales_completed', 'product_category', 'string', 'none', 'product_category', 'Merchandise category of the ordered item.');
INSERT INTO _tmdl_columns VALUES ('duplicated oakhaven template', 'flat_sales_completed', 'quantity', 'string', 'none', 'quantity', 'Number of units purchased in order line.');
INSERT INTO _tmdl_columns VALUES ('duplicated oakhaven template', 'flat_sales_completed', 'net_amount', 'string', 'none', 'net_amount', 'Actual net revenue earned after applying discounts.');
INSERT INTO _tmdl_columns VALUES ('duplicated oakhaven template', 'flat_sales_completed', 'channel', 'string', 'none', 'channel', 'Sales channel origination (Web, Mobile App, In-Store Retail).');
CREATE TABLE IF NOT EXISTS tmdl_duplicated_oakhaven_template_flat_sales_completed (
    order_id TEXT,
    order_line_id TEXT,
    order_date TEXT,
    customer_name TEXT,
    product_name TEXT,
    product_category TEXT,
    quantity TEXT,
    net_amount TEXT,
    channel TEXT,
    FOREIGN KEY (order_date) REFERENCES tmdl_duplicated_oakhaven_template_dim_calendar(date)
);

INSERT OR REPLACE INTO _tmdl_tables VALUES ('duplicated oakhaven template', 'sql_dim_customer', 'None');
INSERT INTO _tmdl_data_sources VALUES ('duplicated oakhaven template', 'sql_dim_customer', 'Relational SQL Source', 'project/oakhaven.db', 'Native SQL Pushdown');
INSERT INTO _tmdl_m_steps VALUES ('duplicated oakhaven template', 'sql_dim_customer', 1, 'Source', 'Source Ingestion', '"SELECT DISTINCT 
    c.customer_id');
INSERT INTO _tmdl_columns VALUES ('duplicated oakhaven template', 'sql_dim_customer', 'sql_dim_customer', 'string', 'none', 'sql_dim_customer', 'Attribute column representing sql_dim_customer.');
CREATE TABLE IF NOT EXISTS tmdl_duplicated_oakhaven_template_sql_dim_customer (
    sql_dim_customer TEXT
);

INSERT OR REPLACE INTO _tmdl_tables VALUES ('duplicated oakhaven template', 'sql_dim_date', 'None');
INSERT INTO _tmdl_data_sources VALUES ('duplicated oakhaven template', 'sql_dim_date', 'Relational SQL Source', 'project/oakhaven.db', 'Native SQL Pushdown');
INSERT INTO _tmdl_m_steps VALUES ('duplicated oakhaven template', 'sql_dim_date', 1, 'Source', 'Source Ingestion', '"SELECT DISTINCT 
    d.datekey');
INSERT INTO _tmdl_columns VALUES ('duplicated oakhaven template', 'sql_dim_date', 'sql_dim_date', 'string', 'none', 'sql_dim_date', 'Attribute column representing sql_dim_date.');
CREATE TABLE IF NOT EXISTS tmdl_duplicated_oakhaven_template_sql_dim_date (
    sql_dim_date TEXT
);

INSERT OR REPLACE INTO _tmdl_tables VALUES ('duplicated oakhaven template', 'sql_dim_employee', 'None');
INSERT INTO _tmdl_data_sources VALUES ('duplicated oakhaven template', 'sql_dim_employee', 'Relational SQL Source', 'project/oakhaven.db', 'Native SQL Pushdown');
INSERT INTO _tmdl_m_steps VALUES ('duplicated oakhaven template', 'sql_dim_employee', 1, 'Source', 'Source Ingestion', '"SELECT DISTINCT 
    e.employee_id');
INSERT INTO _tmdl_columns VALUES ('duplicated oakhaven template', 'sql_dim_employee', 'sql_dim_employee', 'string', 'none', 'sql_dim_employee', 'Attribute column representing sql_dim_employee.');
CREATE TABLE IF NOT EXISTS tmdl_duplicated_oakhaven_template_sql_dim_employee (
    sql_dim_employee TEXT
);

INSERT OR REPLACE INTO _tmdl_tables VALUES ('duplicated oakhaven template', 'sql_dim_product', 'None');
INSERT INTO _tmdl_data_sources VALUES ('duplicated oakhaven template', 'sql_dim_product', 'Relational SQL Source', 'project/oakhaven.db', 'Native SQL Pushdown');
INSERT INTO _tmdl_m_steps VALUES ('duplicated oakhaven template', 'sql_dim_product', 1, 'Source', 'Source Ingestion', '"SELECT DISTINCT 
    p.product_id');
INSERT INTO _tmdl_columns VALUES ('duplicated oakhaven template', 'sql_dim_product', 'sql_dim_product', 'string', 'none', 'sql_dim_product', 'Attribute column representing sql_dim_product.');
CREATE TABLE IF NOT EXISTS tmdl_duplicated_oakhaven_template_sql_dim_product (
    sql_dim_product TEXT
);

INSERT OR REPLACE INTO _tmdl_tables VALUES ('duplicated oakhaven template', 'sql_fact_sales', 'None');
INSERT INTO _tmdl_data_sources VALUES ('duplicated oakhaven template', 'sql_fact_sales', 'Relational SQL Source', 'project/oakhaven.db', 'Native SQL Pushdown');
INSERT INTO _tmdl_m_steps VALUES ('duplicated oakhaven template', 'sql_fact_sales', 1, 'Source', 'Source Ingestion', '"SELECT 
    f.order_id');
INSERT INTO _tmdl_columns VALUES ('duplicated oakhaven template', 'sql_fact_sales', 'sql_fact_sales', 'string', 'none', 'sql_fact_sales', 'Attribute column representing sql_fact_sales.');
CREATE TABLE IF NOT EXISTS tmdl_duplicated_oakhaven_template_sql_fact_sales (
    sql_fact_sales TEXT
);

INSERT OR REPLACE INTO _tmdl_tables VALUES ('duplicated oakhaven template', 'sql_flat_sales_all', 'None');
INSERT INTO _tmdl_data_sources VALUES ('duplicated oakhaven template', 'sql_flat_sales_all', 'Relational SQL Source', 'project/oakhaven.db', 'Native SQL Pushdown');
INSERT INTO _tmdl_m_steps VALUES ('duplicated oakhaven template', 'sql_flat_sales_all', 1, 'Source', 'Source Ingestion', '"SELECT 
    f.order_id');
INSERT INTO _tmdl_m_steps VALUES ('duplicated oakhaven template', 'sql_flat_sales_all', 2, 'customer_id', 'Source Ingestion', 'c.customer_id
LEFT JOIN dim_product p ON f.product_id = p.product_id
LEFT JOIN dim_employee e ON f.e...');
INSERT INTO _tmdl_columns VALUES ('duplicated oakhaven template', 'sql_flat_sales_all', 'sql_flat_sales_all', 'string', 'none', 'sql_flat_sales_all', 'Attribute column representing sql_flat_sales_all.');
CREATE TABLE IF NOT EXISTS tmdl_duplicated_oakhaven_template_sql_flat_sales_all (
    sql_flat_sales_all TEXT
);

INSERT OR REPLACE INTO _tmdl_tables VALUES ('duplicated oakhaven template', 'sql_flat_sales_completed', 'None');
INSERT INTO _tmdl_data_sources VALUES ('duplicated oakhaven template', 'sql_flat_sales_completed', 'Relational SQL Source', 'project/oakhaven.db', 'Native SQL Pushdown');
INSERT INTO _tmdl_m_steps VALUES ('duplicated oakhaven template', 'sql_flat_sales_completed', 1, 'Source', 'Source Ingestion', '"SELECT 
    f.order_id');
INSERT INTO _tmdl_m_steps VALUES ('duplicated oakhaven template', 'sql_flat_sales_completed', 2, 'customer_id', 'Filter Transformation', 'c.customer_id
LEFT JOIN dim_product p ON f.product_id = p.product_id
WHERE f.order_status = ''Complet...');
INSERT INTO _tmdl_columns VALUES ('duplicated oakhaven template', 'sql_flat_sales_completed', 'sql_flat_sales_completed', 'string', 'none', 'sql_flat_sales_completed', 'Attribute column representing sql_flat_sales_completed.');
CREATE TABLE IF NOT EXISTS tmdl_duplicated_oakhaven_template_sql_flat_sales_completed (
    sql_flat_sales_completed TEXT
);

-- PROJECT: flat_sales_all
INSERT OR REPLACE INTO _tmdl_projects VALUES ('flat_sales_all', 4, 4, 1);
INSERT INTO _tmdl_parameters VALUES ('flat_sales_all', 'oakhavendatabasepath', 'Text', 'project/oakhaven.db');
INSERT INTO _tmdl_relationships VALUES ('flat_sales_all', 'AutoDetected_de8de45f-ebb1-4d1d-a6b4-e19e17d854ac', 'fact_sales', 'datekey', 'dim_calendar', 'datekey', 'one');
INSERT INTO _tmdl_relationships VALUES ('flat_sales_all', 'cdcabb57-8502-4d1c-1ca6-c29df34d8d3e', 'fact_sales', 'employee_id', 'dim_employee', 'employee_id', 'one');
INSERT INTO _tmdl_relationships VALUES ('flat_sales_all', 'dab805ef-d296-87a4-acb2-347f07dc4199', 'flat_sales_all', 'order_date', 'dim_calendar', 'date', 'one');
INSERT INTO _tmdl_relationships VALUES ('flat_sales_all', '8defae2f-1aaf-a630-18a1-4f48a16e650a', 'fact_sales', 'order_id', 'flat_sales_all', 'order_id', 'one');
INSERT OR REPLACE INTO _tmdl_tables VALUES ('flat_sales_all', 'dim_calendar', 'None');
INSERT INTO _tmdl_data_sources VALUES ('flat_sales_all', 'dim_calendar', 'SQLite (Python Connector)', '"project/oakhaven.db"', 'Native SQL Pushdown');
INSERT INTO _tmdl_m_steps VALUES ('flat_sales_all', 'dim_calendar', 1, 'Source', 'Source Ingestion', 'Python.Execute("import sqlite3
import pandas as pd
import matplotlib as mpl

conn = sqlite3.connect(...');
INSERT INTO _tmdl_columns VALUES ('flat_sales_all', 'dim_calendar', 'datekey', 'string', 'none', 'datekey', 'Integer surrogate key in YYYYMMDD format for date joins.');
INSERT INTO _tmdl_columns VALUES ('flat_sales_all', 'dim_calendar', 'date', 'string', 'none', 'date', 'Standard ISO 8601 calendar date (YYYY-MM-DD).');
INSERT INTO _tmdl_columns VALUES ('flat_sales_all', 'dim_calendar', 'year', 'string', 'none', 'year', 'Four-digit calendar year (e.g. 2026).');
INSERT INTO _tmdl_columns VALUES ('flat_sales_all', 'dim_calendar', 'month', 'string', 'none', 'month', 'Numeric calendar month (1..12).');
INSERT INTO _tmdl_columns VALUES ('flat_sales_all', 'dim_calendar', 'month_name', 'string', 'none', 'month_name', 'Full English month name (e.g. January, February).');
INSERT INTO _tmdl_columns VALUES ('flat_sales_all', 'dim_calendar', 'quarter', 'string', 'none', 'quarter', 'Calendar quarter identifier (Q1, Q2, Q3, Q4).');
INSERT INTO _tmdl_columns VALUES ('flat_sales_all', 'dim_calendar', 'day_name', 'string', 'none', 'day_name', 'Full English day name (e.g. Monday, Tuesday).');
INSERT INTO _tmdl_columns VALUES ('flat_sales_all', 'dim_calendar', 'is_weekend', 'string', 'none', 'is_weekend', 'Boolean flag indicating Saturday or Sunday (1 = Weekend, 0 = Weekday).');
CREATE TABLE IF NOT EXISTS tmdl_flat_sales_all_dim_calendar (
    datekey TEXT,
    date TEXT,
    year TEXT,
    month TEXT,
    month_name TEXT,
    quarter TEXT,
    day_name TEXT,
    is_weekend TEXT
);

INSERT OR REPLACE INTO _tmdl_tables VALUES ('flat_sales_all', 'dim_employee', 'None');
INSERT INTO _tmdl_data_sources VALUES ('flat_sales_all', 'dim_employee', 'SQLite (Python Connector)', '"project/oakhaven.db"', 'Native SQL Pushdown');
INSERT INTO _tmdl_m_steps VALUES ('flat_sales_all', 'dim_employee', 1, 'Source', 'Source Ingestion', 'Python.Execute("import sqlite3
import pandas as pd
import matplotlib as mpl

conn = sqlite3.connect(...');
INSERT INTO _tmdl_columns VALUES ('flat_sales_all', 'dim_employee', 'employee_id', 'string', 'none', 'employee_id', 'Unique employee identification number (1..35).');
INSERT INTO _tmdl_columns VALUES ('flat_sales_all', 'dim_employee', 'full_name', 'string', 'none', 'full_name', 'Concatenated customer full name (first + last).');
INSERT INTO _tmdl_columns VALUES ('flat_sales_all', 'dim_employee', 'department', 'string', 'none', 'department', 'Company department (Sales, Support, Warehouse, Management).');
INSERT INTO _tmdl_columns VALUES ('flat_sales_all', 'dim_employee', 'region', 'string', 'none', 'region', 'Assigned geographical sales territory (West, East, Central, South).');
CREATE TABLE IF NOT EXISTS tmdl_flat_sales_all_dim_employee (
    employee_id TEXT,
    full_name TEXT,
    department TEXT,
    region TEXT
);

INSERT OR REPLACE INTO _tmdl_tables VALUES ('flat_sales_all', 'fact_sales', 'None');
INSERT INTO _tmdl_data_sources VALUES ('flat_sales_all', 'fact_sales', 'SQLite (Python Connector)', '"project/oakhaven.db"', 'Native SQL Pushdown');
INSERT INTO _tmdl_m_steps VALUES ('flat_sales_all', 'fact_sales', 1, 'Source', 'Source Ingestion', 'Python.Execute("import sqlite3
import pandas as pd
import matplotlib as mpl

conn = sqlite3.connect(...');
INSERT INTO _tmdl_m_steps VALUES ('flat_sales_all', 'fact_sales', 2, 'DataTable', 'Source Ingestion', 'Source{[Name="df"]}[Value]');
INSERT INTO _tmdl_columns VALUES ('flat_sales_all', 'fact_sales', 'order_id', 'string', 'none', 'order_id', 'Unique sales order transaction header identifier.');
INSERT INTO _tmdl_columns VALUES ('flat_sales_all', 'fact_sales', 'order_line_id', 'string', 'none', 'order_line_id', 'Line item sequence number (1..N) within an order.');
INSERT INTO _tmdl_columns VALUES ('flat_sales_all', 'fact_sales', 'customer_id', 'string', 'none', 'customer_id', 'Unique sequential identifier (1..600) for each customer.');
INSERT INTO _tmdl_columns VALUES ('flat_sales_all', 'fact_sales', 'product_id', 'string', 'none', 'product_id', 'Unique surrogate key (1..150) identifying each merchandise item.');
INSERT INTO _tmdl_columns VALUES ('flat_sales_all', 'fact_sales', 'employee_id', 'string', 'none', 'employee_id', 'Unique employee identification number (1..35).');
INSERT INTO _tmdl_columns VALUES ('flat_sales_all', 'fact_sales', 'datekey', 'string', 'none', 'datekey', 'Integer surrogate key in YYYYMMDD format for date joins.');
INSERT INTO _tmdl_columns VALUES ('flat_sales_all', 'fact_sales', 'quantity', 'string', 'none', 'quantity', 'Number of units purchased in order line.');
INSERT INTO _tmdl_columns VALUES ('flat_sales_all', 'fact_sales', 'unit_price', 'string', 'none', 'unit_price', 'Retail selling price per unit ($) at time of order.');
INSERT INTO _tmdl_columns VALUES ('flat_sales_all', 'fact_sales', 'discount_pct', 'string', 'none', 'discount_pct', 'Percentage discount applied (0.00 to 0.30).');
INSERT INTO _tmdl_columns VALUES ('flat_sales_all', 'fact_sales', 'net_amount', 'string', 'none', 'net_amount', 'Actual net revenue earned after applying discounts.');
INSERT INTO _tmdl_columns VALUES ('flat_sales_all', 'fact_sales', 'payment_method', 'string', 'none', 'payment_method', 'Payment tender channel (Credit Card, PayPal, Cash, Debit Card).');
INSERT INTO _tmdl_columns VALUES ('flat_sales_all', 'fact_sales', 'order_status', 'string', 'none', 'order_status', 'Current status of transaction (Completed, Processing, Canceled, Returned).');
INSERT INTO _tmdl_columns VALUES ('flat_sales_all', 'fact_sales', 'channel', 'string', 'none', 'channel', 'Sales channel origination (Web, Mobile App, In-Store Retail).');
CREATE TABLE IF NOT EXISTS tmdl_flat_sales_all_fact_sales (
    order_id TEXT,
    order_line_id TEXT,
    customer_id TEXT,
    product_id TEXT,
    employee_id TEXT,
    datekey TEXT,
    quantity TEXT,
    unit_price TEXT,
    discount_pct TEXT,
    net_amount TEXT,
    payment_method TEXT,
    order_status TEXT,
    channel TEXT,
    FOREIGN KEY (datekey) REFERENCES tmdl_flat_sales_all_dim_calendar(datekey),
    FOREIGN KEY (employee_id) REFERENCES tmdl_flat_sales_all_dim_employee(employee_id),
    FOREIGN KEY (order_id) REFERENCES tmdl_flat_sales_all_flat_sales_all(order_id)
);

INSERT OR REPLACE INTO _tmdl_tables VALUES ('flat_sales_all', 'flat_sales_all', 'None');
INSERT INTO _tmdl_data_sources VALUES ('flat_sales_all', 'flat_sales_all', 'SQLite (Python Connector)', '"project/oakhaven.db"', 'Native SQL Pushdown');
INSERT INTO _tmdl_m_steps VALUES ('flat_sales_all', 'flat_sales_all', 1, 'Source', 'Source Ingestion', 'Python.Execute("import sqlite3
import pandas as pd
import matplotlib as mpl

conn = sqlite3.connect(...');
INSERT INTO _tmdl_m_steps VALUES ('flat_sales_all', 'flat_sales_all', 2, 'DataTable', 'Source Ingestion', 'Source{[Name="df"]}[Value]');
INSERT INTO _tmdl_columns VALUES ('flat_sales_all', 'flat_sales_all', 'order_id', 'string', 'none', 'order_id', 'Unique sales order transaction header identifier.');
INSERT INTO _tmdl_columns VALUES ('flat_sales_all', 'flat_sales_all', 'order_line_id', 'string', 'none', 'order_line_id', 'Line item sequence number (1..N) within an order.');
INSERT INTO _tmdl_columns VALUES ('flat_sales_all', 'flat_sales_all', 'order_date', 'string', 'none', 'order_date', 'Transaction date on which order was placed.');
INSERT INTO _tmdl_columns VALUES ('flat_sales_all', 'flat_sales_all', 'customer_name', 'string', 'none', 'customer_name', 'Full name of the purchasing customer.');
INSERT INTO _tmdl_columns VALUES ('flat_sales_all', 'flat_sales_all', 'product_name', 'string', 'none', 'product_name', 'Catalog description and product title.');
INSERT INTO _tmdl_columns VALUES ('flat_sales_all', 'flat_sales_all', 'product_category', 'string', 'none', 'product_category', 'Merchandise category of the ordered item.');
INSERT INTO _tmdl_columns VALUES ('flat_sales_all', 'flat_sales_all', 'quantity', 'string', 'none', 'quantity', 'Number of units purchased in order line.');
INSERT INTO _tmdl_columns VALUES ('flat_sales_all', 'flat_sales_all', 'net_amount', 'string', 'none', 'net_amount', 'Actual net revenue earned after applying discounts.');
INSERT INTO _tmdl_columns VALUES ('flat_sales_all', 'flat_sales_all', 'channel', 'string', 'none', 'channel', 'Sales channel origination (Web, Mobile App, In-Store Retail).');
CREATE TABLE IF NOT EXISTS tmdl_flat_sales_all_flat_sales_all (
    order_id TEXT,
    order_line_id TEXT,
    order_date TEXT,
    customer_name TEXT,
    product_name TEXT,
    product_category TEXT,
    quantity TEXT,
    net_amount TEXT,
    channel TEXT,
    FOREIGN KEY (order_date) REFERENCES tmdl_flat_sales_all_dim_calendar(date)
);

-- PROJECT: flat_sales_completed
INSERT OR REPLACE INTO _tmdl_projects VALUES ('flat_sales_completed', 7, 1, 1);
INSERT INTO _tmdl_parameters VALUES ('flat_sales_completed', 'oakhavendatabasepath', 'Text', 'project/oakhaven.db');
INSERT INTO _tmdl_relationships VALUES ('flat_sales_completed', 'defc8ca4-33ee-19ab-d42b-240fcd45be3e', 'flat_sales_completed', 'order_date', 'dim_calendar', 'date', 'one');
INSERT OR REPLACE INTO _tmdl_tables VALUES ('flat_sales_completed', 'dim_calendar', 'None');
INSERT INTO _tmdl_data_sources VALUES ('flat_sales_completed', 'dim_calendar', 'SQLite (Python Connector)', '"project/oakhaven.db"', 'Native SQL Pushdown');
INSERT INTO _tmdl_m_steps VALUES ('flat_sales_completed', 'dim_calendar', 1, 'Source', 'Source Ingestion', 'Python.Execute("import sqlite3
import pandas as pd
import matplotlib as mpl

conn = sqlite3.connect(...');
INSERT INTO _tmdl_columns VALUES ('flat_sales_completed', 'dim_calendar', 'datekey', 'string', 'none', 'datekey', 'Integer surrogate key in YYYYMMDD format for date joins.');
INSERT INTO _tmdl_columns VALUES ('flat_sales_completed', 'dim_calendar', 'date', 'string', 'none', 'date', 'Standard ISO 8601 calendar date (YYYY-MM-DD).');
INSERT INTO _tmdl_columns VALUES ('flat_sales_completed', 'dim_calendar', 'year', 'string', 'none', 'year', 'Four-digit calendar year (e.g. 2026).');
INSERT INTO _tmdl_columns VALUES ('flat_sales_completed', 'dim_calendar', 'month', 'string', 'none', 'month', 'Numeric calendar month (1..12).');
INSERT INTO _tmdl_columns VALUES ('flat_sales_completed', 'dim_calendar', 'month_name', 'string', 'none', 'month_name', 'Full English month name (e.g. January, February).');
INSERT INTO _tmdl_columns VALUES ('flat_sales_completed', 'dim_calendar', 'quarter', 'string', 'none', 'quarter', 'Calendar quarter identifier (Q1, Q2, Q3, Q4).');
INSERT INTO _tmdl_columns VALUES ('flat_sales_completed', 'dim_calendar', 'day_name', 'string', 'none', 'day_name', 'Full English day name (e.g. Monday, Tuesday).');
INSERT INTO _tmdl_columns VALUES ('flat_sales_completed', 'dim_calendar', 'is_weekend', 'string', 'none', 'is_weekend', 'Boolean flag indicating Saturday or Sunday (1 = Weekend, 0 = Weekday).');
CREATE TABLE IF NOT EXISTS tmdl_flat_sales_completed_dim_calendar (
    datekey TEXT,
    date TEXT,
    year TEXT,
    month TEXT,
    month_name TEXT,
    quarter TEXT,
    day_name TEXT,
    is_weekend TEXT
);

INSERT OR REPLACE INTO _tmdl_tables VALUES ('flat_sales_completed', 'dim_customer', 'None');
INSERT INTO _tmdl_data_sources VALUES ('flat_sales_completed', 'dim_customer', 'SQLite (Python Connector)', '"project/oakhaven.db"', 'Native SQL Pushdown');
INSERT INTO _tmdl_m_steps VALUES ('flat_sales_completed', 'dim_customer', 1, 'Source', 'Source Ingestion', 'Python.Execute("import sqlite3
import pandas as pd
import matplotlib as mpl

conn = sqlite3.connect(...');
INSERT INTO _tmdl_columns VALUES ('flat_sales_completed', 'dim_customer', 'customer_id', 'string', 'none', 'customer_id', 'Unique sequential identifier (1..600) for each customer.');
INSERT INTO _tmdl_columns VALUES ('flat_sales_completed', 'dim_customer', 'full_name', 'string', 'none', 'full_name', 'Concatenated customer full name (first + last).');
INSERT INTO _tmdl_columns VALUES ('flat_sales_completed', 'dim_customer', 'email', 'string', 'none', 'email', 'Primary email address associated with customer account.');
INSERT INTO _tmdl_columns VALUES ('flat_sales_completed', 'dim_customer', 'state', 'string', 'none', 'state', 'Customer geographic state or province code.');
INSERT INTO _tmdl_columns VALUES ('flat_sales_completed', 'dim_customer', 'customer_segment', 'string', 'none', 'customer_segment', 'Market segment classification (Retail, Wholesale, VIP).');
CREATE TABLE IF NOT EXISTS tmdl_flat_sales_completed_dim_customer (
    customer_id TEXT,
    full_name TEXT,
    email TEXT,
    state TEXT,
    customer_segment TEXT
);

INSERT OR REPLACE INTO _tmdl_tables VALUES ('flat_sales_completed', 'flat_sales_completed', 'None');
INSERT INTO _tmdl_data_sources VALUES ('flat_sales_completed', 'flat_sales_completed', 'SQLite (Python Connector)', '"project/oakhaven.db"', 'Native SQL Pushdown');
INSERT INTO _tmdl_m_steps VALUES ('flat_sales_completed', 'flat_sales_completed', 1, 'Source', 'Source Ingestion', 'Python.Execute("import sqlite3
import pandas as pd
import matplotlib as mpl

conn = sqlite3.connect(...');
INSERT INTO _tmdl_m_steps VALUES ('flat_sales_completed', 'flat_sales_completed', 2, 'customer_id', 'Filter Transformation', 'c.customer_id
LEFT JOIN dim_product p ON f.product_id = p.product_id
WHERE f.order_status = ''Complet...');
INSERT INTO _tmdl_m_steps VALUES ('flat_sales_completed', 'flat_sales_completed', 3, 'DataTable', 'Source Ingestion', 'Source{[Name="df"]}[Value]');
INSERT INTO _tmdl_columns VALUES ('flat_sales_completed', 'flat_sales_completed', 'order_id', 'string', 'none', 'order_id', 'Unique sales order transaction header identifier.');
INSERT INTO _tmdl_columns VALUES ('flat_sales_completed', 'flat_sales_completed', 'order_line_id', 'string', 'none', 'order_line_id', 'Line item sequence number (1..N) within an order.');
INSERT INTO _tmdl_columns VALUES ('flat_sales_completed', 'flat_sales_completed', 'order_date', 'string', 'none', 'order_date', 'Transaction date on which order was placed.');
INSERT INTO _tmdl_columns VALUES ('flat_sales_completed', 'flat_sales_completed', 'customer_name', 'string', 'none', 'customer_name', 'Full name of the purchasing customer.');
INSERT INTO _tmdl_columns VALUES ('flat_sales_completed', 'flat_sales_completed', 'product_name', 'string', 'none', 'product_name', 'Catalog description and product title.');
INSERT INTO _tmdl_columns VALUES ('flat_sales_completed', 'flat_sales_completed', 'product_category', 'string', 'none', 'product_category', 'Merchandise category of the ordered item.');
INSERT INTO _tmdl_columns VALUES ('flat_sales_completed', 'flat_sales_completed', 'quantity', 'string', 'none', 'quantity', 'Number of units purchased in order line.');
INSERT INTO _tmdl_columns VALUES ('flat_sales_completed', 'flat_sales_completed', 'net_amount', 'string', 'none', 'net_amount', 'Actual net revenue earned after applying discounts.');
INSERT INTO _tmdl_columns VALUES ('flat_sales_completed', 'flat_sales_completed', 'channel', 'string', 'none', 'channel', 'Sales channel origination (Web, Mobile App, In-Store Retail).');
CREATE TABLE IF NOT EXISTS tmdl_flat_sales_completed_flat_sales_completed (
    order_id TEXT,
    order_line_id TEXT,
    order_date TEXT,
    customer_name TEXT,
    product_name TEXT,
    product_category TEXT,
    quantity TEXT,
    net_amount TEXT,
    channel TEXT,
    FOREIGN KEY (order_date) REFERENCES tmdl_flat_sales_completed_dim_calendar(date)
);

INSERT OR REPLACE INTO _tmdl_tables VALUES ('flat_sales_completed', 'sql_dim_date', 'None');
INSERT INTO _tmdl_data_sources VALUES ('flat_sales_completed', 'sql_dim_date', 'Relational SQL Source', 'project/oakhaven.db', 'Native SQL Pushdown');
INSERT INTO _tmdl_m_steps VALUES ('flat_sales_completed', 'sql_dim_date', 1, 'Source', 'Source Ingestion', '"SELECT DISTINCT 
    d.datekey');
INSERT INTO _tmdl_columns VALUES ('flat_sales_completed', 'sql_dim_date', 'sql_dim_date', 'string', 'none', 'sql_dim_date', 'Attribute column representing sql_dim_date.');
CREATE TABLE IF NOT EXISTS tmdl_flat_sales_completed_sql_dim_date (
    sql_dim_date TEXT
);

INSERT OR REPLACE INTO _tmdl_tables VALUES ('flat_sales_completed', 'sql_dim_product', 'None');
INSERT INTO _tmdl_data_sources VALUES ('flat_sales_completed', 'sql_dim_product', 'Relational SQL Source', 'project/oakhaven.db', 'Native SQL Pushdown');
INSERT INTO _tmdl_m_steps VALUES ('flat_sales_completed', 'sql_dim_product', 1, 'Source', 'Source Ingestion', '"SELECT DISTINCT 
    p.product_id');
INSERT INTO _tmdl_columns VALUES ('flat_sales_completed', 'sql_dim_product', 'sql_dim_product', 'string', 'none', 'sql_dim_product', 'Attribute column representing sql_dim_product.');
CREATE TABLE IF NOT EXISTS tmdl_flat_sales_completed_sql_dim_product (
    sql_dim_product TEXT
);

INSERT OR REPLACE INTO _tmdl_tables VALUES ('flat_sales_completed', 'sql_flat_sales_all', 'None');
INSERT INTO _tmdl_data_sources VALUES ('flat_sales_completed', 'sql_flat_sales_all', 'Relational SQL Source', 'project/oakhaven.db', 'Native SQL Pushdown');
INSERT INTO _tmdl_m_steps VALUES ('flat_sales_completed', 'sql_flat_sales_all', 1, 'Source', 'Source Ingestion', '"SELECT 
    f.order_id');
INSERT INTO _tmdl_m_steps VALUES ('flat_sales_completed', 'sql_flat_sales_all', 2, 'customer_id', 'Source Ingestion', 'c.customer_id
LEFT JOIN dim_product p ON f.product_id = p.product_id
LEFT JOIN dim_employee e ON f.e...');
INSERT INTO _tmdl_columns VALUES ('flat_sales_completed', 'sql_flat_sales_all', 'sql_flat_sales_all', 'string', 'none', 'sql_flat_sales_all', 'Attribute column representing sql_flat_sales_all.');
CREATE TABLE IF NOT EXISTS tmdl_flat_sales_completed_sql_flat_sales_all (
    sql_flat_sales_all TEXT
);

INSERT OR REPLACE INTO _tmdl_tables VALUES ('flat_sales_completed', 'sql_flat_sales_completed', 'None');
INSERT INTO _tmdl_data_sources VALUES ('flat_sales_completed', 'sql_flat_sales_completed', 'Relational SQL Source', 'project/oakhaven.db', 'Native SQL Pushdown');
INSERT INTO _tmdl_m_steps VALUES ('flat_sales_completed', 'sql_flat_sales_completed', 1, 'Source', 'Source Ingestion', '"SELECT 
    f.order_id');
INSERT INTO _tmdl_m_steps VALUES ('flat_sales_completed', 'sql_flat_sales_completed', 2, 'customer_id', 'Filter Transformation', 'c.customer_id
LEFT JOIN dim_product p ON f.product_id = p.product_id
WHERE f.order_status = ''Complet...');
INSERT INTO _tmdl_columns VALUES ('flat_sales_completed', 'sql_flat_sales_completed', 'sql_flat_sales_completed', 'string', 'none', 'sql_flat_sales_completed', 'Attribute column representing sql_flat_sales_completed.');
CREATE TABLE IF NOT EXISTS tmdl_flat_sales_completed_sql_flat_sales_completed (
    sql_flat_sales_completed TEXT
);

-- PROJECT: oakhaven template
INSERT OR REPLACE INTO _tmdl_projects VALUES ('oakhaven template', 13, 5, 1);
INSERT INTO _tmdl_parameters VALUES ('oakhaven template', 'oakhavendatabasepath', 'Text', 'project/oakhaven.db');
INSERT INTO _tmdl_relationships VALUES ('oakhaven template', 'AutoDetected_1d28b393-7c5a-472e-8bdf-bbaefdfadc47', 'fact_sales', 'customer_id', 'dim_customer', 'customer_id', 'one');
INSERT INTO _tmdl_relationships VALUES ('oakhaven template', 'AutoDetected_de8de45f-ebb1-4d1d-a6b4-e19e17d854ac', 'fact_sales', 'datekey', 'dim_calendar', 'datekey', 'one');
INSERT INTO _tmdl_relationships VALUES ('oakhaven template', 'cdcabb57-8502-4d1c-1ca6-c29df34d8d3e', 'fact_sales', 'employee_id', 'dim_employee', 'employee_id', 'one');
INSERT INTO _tmdl_relationships VALUES ('oakhaven template', 'dab805ef-d296-87a4-acb2-347f07dc4199', 'flat_sales_all', 'order_date', 'dim_calendar', 'date', 'one');
INSERT INTO _tmdl_relationships VALUES ('oakhaven template', 'defc8ca4-33ee-19ab-d42b-240fcd45be3e', 'flat_sales_completed', 'order_date', 'dim_calendar', 'date', 'one');
INSERT OR REPLACE INTO _tmdl_tables VALUES ('oakhaven template', 'dim_calendar', 'None');
INSERT INTO _tmdl_data_sources VALUES ('oakhaven template', 'dim_calendar', 'SQLite (Python Connector)', '"project/oakhaven.db"', 'Native SQL Pushdown');
INSERT INTO _tmdl_m_steps VALUES ('oakhaven template', 'dim_calendar', 1, 'Source', 'Source Ingestion', 'Python.Execute("import sqlite3
import pandas as pd
import matplotlib as mpl

conn = sqlite3.connect(...');
INSERT INTO _tmdl_columns VALUES ('oakhaven template', 'dim_calendar', 'datekey', 'string', 'none', 'datekey', 'Integer surrogate key in YYYYMMDD format for date joins.');
INSERT INTO _tmdl_columns VALUES ('oakhaven template', 'dim_calendar', 'date', 'string', 'none', 'date', 'Standard ISO 8601 calendar date (YYYY-MM-DD).');
INSERT INTO _tmdl_columns VALUES ('oakhaven template', 'dim_calendar', 'year', 'string', 'none', 'year', 'Four-digit calendar year (e.g. 2026).');
INSERT INTO _tmdl_columns VALUES ('oakhaven template', 'dim_calendar', 'month', 'string', 'none', 'month', 'Numeric calendar month (1..12).');
INSERT INTO _tmdl_columns VALUES ('oakhaven template', 'dim_calendar', 'month_name', 'string', 'none', 'month_name', 'Full English month name (e.g. January, February).');
INSERT INTO _tmdl_columns VALUES ('oakhaven template', 'dim_calendar', 'quarter', 'string', 'none', 'quarter', 'Calendar quarter identifier (Q1, Q2, Q3, Q4).');
INSERT INTO _tmdl_columns VALUES ('oakhaven template', 'dim_calendar', 'day_name', 'string', 'none', 'day_name', 'Full English day name (e.g. Monday, Tuesday).');
INSERT INTO _tmdl_columns VALUES ('oakhaven template', 'dim_calendar', 'is_weekend', 'string', 'none', 'is_weekend', 'Boolean flag indicating Saturday or Sunday (1 = Weekend, 0 = Weekday).');
CREATE TABLE IF NOT EXISTS tmdl_oakhaven_template_dim_calendar (
    datekey TEXT,
    date TEXT,
    year TEXT,
    month TEXT,
    month_name TEXT,
    quarter TEXT,
    day_name TEXT,
    is_weekend TEXT
);

INSERT OR REPLACE INTO _tmdl_tables VALUES ('oakhaven template', 'dim_customer', 'None');
INSERT INTO _tmdl_data_sources VALUES ('oakhaven template', 'dim_customer', 'SQLite (Python Connector)', '"project/oakhaven.db"', 'Native SQL Pushdown');
INSERT INTO _tmdl_m_steps VALUES ('oakhaven template', 'dim_customer', 1, 'Source', 'Source Ingestion', 'Python.Execute("import sqlite3
import pandas as pd
import matplotlib as mpl

conn = sqlite3.connect(...');
INSERT INTO _tmdl_columns VALUES ('oakhaven template', 'dim_customer', 'customer_id', 'string', 'none', 'customer_id', 'Unique sequential identifier (1..600) for each customer.');
INSERT INTO _tmdl_columns VALUES ('oakhaven template', 'dim_customer', 'full_name', 'string', 'none', 'full_name', 'Concatenated customer full name (first + last).');
INSERT INTO _tmdl_columns VALUES ('oakhaven template', 'dim_customer', 'email', 'string', 'none', 'email', 'Primary email address associated with customer account.');
INSERT INTO _tmdl_columns VALUES ('oakhaven template', 'dim_customer', 'state', 'string', 'none', 'state', 'Customer geographic state or province code.');
INSERT INTO _tmdl_columns VALUES ('oakhaven template', 'dim_customer', 'customer_segment', 'string', 'none', 'customer_segment', 'Market segment classification (Retail, Wholesale, VIP).');
CREATE TABLE IF NOT EXISTS tmdl_oakhaven_template_dim_customer (
    customer_id TEXT,
    full_name TEXT,
    email TEXT,
    state TEXT,
    customer_segment TEXT
);

INSERT OR REPLACE INTO _tmdl_tables VALUES ('oakhaven template', 'dim_employee', 'None');
INSERT INTO _tmdl_data_sources VALUES ('oakhaven template', 'dim_employee', 'SQLite (Python Connector)', '"project/oakhaven.db"', 'Native SQL Pushdown');
INSERT INTO _tmdl_m_steps VALUES ('oakhaven template', 'dim_employee', 1, 'Source', 'Source Ingestion', 'Python.Execute("import sqlite3
import pandas as pd
import matplotlib as mpl

conn = sqlite3.connect(...');
INSERT INTO _tmdl_columns VALUES ('oakhaven template', 'dim_employee', 'employee_id', 'string', 'none', 'employee_id', 'Unique employee identification number (1..35).');
INSERT INTO _tmdl_columns VALUES ('oakhaven template', 'dim_employee', 'full_name', 'string', 'none', 'full_name', 'Concatenated customer full name (first + last).');
INSERT INTO _tmdl_columns VALUES ('oakhaven template', 'dim_employee', 'department', 'string', 'none', 'department', 'Company department (Sales, Support, Warehouse, Management).');
INSERT INTO _tmdl_columns VALUES ('oakhaven template', 'dim_employee', 'region', 'string', 'none', 'region', 'Assigned geographical sales territory (West, East, Central, South).');
CREATE TABLE IF NOT EXISTS tmdl_oakhaven_template_dim_employee (
    employee_id TEXT,
    full_name TEXT,
    department TEXT,
    region TEXT
);

INSERT OR REPLACE INTO _tmdl_tables VALUES ('oakhaven template', 'fact_sales', 'None');
INSERT INTO _tmdl_data_sources VALUES ('oakhaven template', 'fact_sales', 'SQLite (Python Connector)', '"project/oakhaven.db"', 'Native SQL Pushdown');
INSERT INTO _tmdl_m_steps VALUES ('oakhaven template', 'fact_sales', 1, 'Source', 'Source Ingestion', 'Python.Execute("import sqlite3
import pandas as pd
import matplotlib as mpl

conn = sqlite3.connect(...');
INSERT INTO _tmdl_m_steps VALUES ('oakhaven template', 'fact_sales', 2, 'DataTable', 'Source Ingestion', 'Source{[Name="df"]}[Value]');
INSERT INTO _tmdl_columns VALUES ('oakhaven template', 'fact_sales', 'order_id', 'string', 'none', 'order_id', 'Unique sales order transaction header identifier.');
INSERT INTO _tmdl_columns VALUES ('oakhaven template', 'fact_sales', 'order_line_id', 'string', 'none', 'order_line_id', 'Line item sequence number (1..N) within an order.');
INSERT INTO _tmdl_columns VALUES ('oakhaven template', 'fact_sales', 'customer_id', 'string', 'none', 'customer_id', 'Unique sequential identifier (1..600) for each customer.');
INSERT INTO _tmdl_columns VALUES ('oakhaven template', 'fact_sales', 'product_id', 'string', 'none', 'product_id', 'Unique surrogate key (1..150) identifying each merchandise item.');
INSERT INTO _tmdl_columns VALUES ('oakhaven template', 'fact_sales', 'employee_id', 'string', 'none', 'employee_id', 'Unique employee identification number (1..35).');
INSERT INTO _tmdl_columns VALUES ('oakhaven template', 'fact_sales', 'datekey', 'string', 'none', 'datekey', 'Integer surrogate key in YYYYMMDD format for date joins.');
INSERT INTO _tmdl_columns VALUES ('oakhaven template', 'fact_sales', 'quantity', 'string', 'none', 'quantity', 'Number of units purchased in order line.');
INSERT INTO _tmdl_columns VALUES ('oakhaven template', 'fact_sales', 'unit_price', 'string', 'none', 'unit_price', 'Retail selling price per unit ($) at time of order.');
INSERT INTO _tmdl_columns VALUES ('oakhaven template', 'fact_sales', 'discount_pct', 'string', 'none', 'discount_pct', 'Percentage discount applied (0.00 to 0.30).');
INSERT INTO _tmdl_columns VALUES ('oakhaven template', 'fact_sales', 'net_amount', 'string', 'none', 'net_amount', 'Actual net revenue earned after applying discounts.');
INSERT INTO _tmdl_columns VALUES ('oakhaven template', 'fact_sales', 'payment_method', 'string', 'none', 'payment_method', 'Payment tender channel (Credit Card, PayPal, Cash, Debit Card).');
INSERT INTO _tmdl_columns VALUES ('oakhaven template', 'fact_sales', 'order_status', 'string', 'none', 'order_status', 'Current status of transaction (Completed, Processing, Canceled, Returned).');
INSERT INTO _tmdl_columns VALUES ('oakhaven template', 'fact_sales', 'channel', 'string', 'none', 'channel', 'Sales channel origination (Web, Mobile App, In-Store Retail).');
CREATE TABLE IF NOT EXISTS tmdl_oakhaven_template_fact_sales (
    order_id TEXT,
    order_line_id TEXT,
    customer_id TEXT,
    product_id TEXT,
    employee_id TEXT,
    datekey TEXT,
    quantity TEXT,
    unit_price TEXT,
    discount_pct TEXT,
    net_amount TEXT,
    payment_method TEXT,
    order_status TEXT,
    channel TEXT,
    FOREIGN KEY (customer_id) REFERENCES tmdl_oakhaven_template_dim_customer(customer_id),
    FOREIGN KEY (datekey) REFERENCES tmdl_oakhaven_template_dim_calendar(datekey),
    FOREIGN KEY (employee_id) REFERENCES tmdl_oakhaven_template_dim_employee(employee_id)
);

INSERT OR REPLACE INTO _tmdl_tables VALUES ('oakhaven template', 'flat_sales_all', 'None');
INSERT INTO _tmdl_data_sources VALUES ('oakhaven template', 'flat_sales_all', 'SQLite (Python Connector)', '"project/oakhaven.db"', 'Native SQL Pushdown');
INSERT INTO _tmdl_m_steps VALUES ('oakhaven template', 'flat_sales_all', 1, 'Source', 'Source Ingestion', 'Python.Execute("import sqlite3
import pandas as pd
import matplotlib as mpl

conn = sqlite3.connect(...');
INSERT INTO _tmdl_m_steps VALUES ('oakhaven template', 'flat_sales_all', 2, 'DataTable', 'Source Ingestion', 'Source{[Name="df"]}[Value]');
INSERT INTO _tmdl_columns VALUES ('oakhaven template', 'flat_sales_all', 'order_id', 'string', 'none', 'order_id', 'Unique sales order transaction header identifier.');
INSERT INTO _tmdl_columns VALUES ('oakhaven template', 'flat_sales_all', 'order_line_id', 'string', 'none', 'order_line_id', 'Line item sequence number (1..N) within an order.');
INSERT INTO _tmdl_columns VALUES ('oakhaven template', 'flat_sales_all', 'order_date', 'string', 'none', 'order_date', 'Transaction date on which order was placed.');
INSERT INTO _tmdl_columns VALUES ('oakhaven template', 'flat_sales_all', 'customer_name', 'string', 'none', 'customer_name', 'Full name of the purchasing customer.');
INSERT INTO _tmdl_columns VALUES ('oakhaven template', 'flat_sales_all', 'product_name', 'string', 'none', 'product_name', 'Catalog description and product title.');
INSERT INTO _tmdl_columns VALUES ('oakhaven template', 'flat_sales_all', 'product_category', 'string', 'none', 'product_category', 'Merchandise category of the ordered item.');
INSERT INTO _tmdl_columns VALUES ('oakhaven template', 'flat_sales_all', 'quantity', 'string', 'none', 'quantity', 'Number of units purchased in order line.');
INSERT INTO _tmdl_columns VALUES ('oakhaven template', 'flat_sales_all', 'net_amount', 'string', 'none', 'net_amount', 'Actual net revenue earned after applying discounts.');
INSERT INTO _tmdl_columns VALUES ('oakhaven template', 'flat_sales_all', 'channel', 'string', 'none', 'channel', 'Sales channel origination (Web, Mobile App, In-Store Retail).');
CREATE TABLE IF NOT EXISTS tmdl_oakhaven_template_flat_sales_all (
    order_id TEXT,
    order_line_id TEXT,
    order_date TEXT,
    customer_name TEXT,
    product_name TEXT,
    product_category TEXT,
    quantity TEXT,
    net_amount TEXT,
    channel TEXT,
    FOREIGN KEY (order_date) REFERENCES tmdl_oakhaven_template_dim_calendar(date)
);

INSERT OR REPLACE INTO _tmdl_tables VALUES ('oakhaven template', 'flat_sales_completed', 'None');
INSERT INTO _tmdl_data_sources VALUES ('oakhaven template', 'flat_sales_completed', 'SQLite (Python Connector)', '"project/oakhaven.db"', 'Native SQL Pushdown');
INSERT INTO _tmdl_m_steps VALUES ('oakhaven template', 'flat_sales_completed', 1, 'Source', 'Source Ingestion', 'Python.Execute("import sqlite3
import pandas as pd
import matplotlib as mpl

conn = sqlite3.connect(...');
INSERT INTO _tmdl_m_steps VALUES ('oakhaven template', 'flat_sales_completed', 2, 'customer_id', 'Filter Transformation', 'c.customer_id
LEFT JOIN dim_product p ON f.product_id = p.product_id
WHERE f.order_status = ''Complet...');
INSERT INTO _tmdl_m_steps VALUES ('oakhaven template', 'flat_sales_completed', 3, 'DataTable', 'Source Ingestion', 'Source{[Name="df"]}[Value]');
INSERT INTO _tmdl_columns VALUES ('oakhaven template', 'flat_sales_completed', 'order_id', 'string', 'none', 'order_id', 'Unique sales order transaction header identifier.');
INSERT INTO _tmdl_columns VALUES ('oakhaven template', 'flat_sales_completed', 'order_line_id', 'string', 'none', 'order_line_id', 'Line item sequence number (1..N) within an order.');
INSERT INTO _tmdl_columns VALUES ('oakhaven template', 'flat_sales_completed', 'order_date', 'string', 'none', 'order_date', 'Transaction date on which order was placed.');
INSERT INTO _tmdl_columns VALUES ('oakhaven template', 'flat_sales_completed', 'customer_name', 'string', 'none', 'customer_name', 'Full name of the purchasing customer.');
INSERT INTO _tmdl_columns VALUES ('oakhaven template', 'flat_sales_completed', 'product_name', 'string', 'none', 'product_name', 'Catalog description and product title.');
INSERT INTO _tmdl_columns VALUES ('oakhaven template', 'flat_sales_completed', 'product_category', 'string', 'none', 'product_category', 'Merchandise category of the ordered item.');
INSERT INTO _tmdl_columns VALUES ('oakhaven template', 'flat_sales_completed', 'quantity', 'string', 'none', 'quantity', 'Number of units purchased in order line.');
INSERT INTO _tmdl_columns VALUES ('oakhaven template', 'flat_sales_completed', 'net_amount', 'string', 'none', 'net_amount', 'Actual net revenue earned after applying discounts.');
INSERT INTO _tmdl_columns VALUES ('oakhaven template', 'flat_sales_completed', 'channel', 'string', 'none', 'channel', 'Sales channel origination (Web, Mobile App, In-Store Retail).');
CREATE TABLE IF NOT EXISTS tmdl_oakhaven_template_flat_sales_completed (
    order_id TEXT,
    order_line_id TEXT,
    order_date TEXT,
    customer_name TEXT,
    product_name TEXT,
    product_category TEXT,
    quantity TEXT,
    net_amount TEXT,
    channel TEXT,
    FOREIGN KEY (order_date) REFERENCES tmdl_oakhaven_template_dim_calendar(date)
);

INSERT OR REPLACE INTO _tmdl_tables VALUES ('oakhaven template', 'sql_dim_customer', 'None');
INSERT INTO _tmdl_data_sources VALUES ('oakhaven template', 'sql_dim_customer', 'Relational SQL Source', 'project/oakhaven.db', 'Native SQL Pushdown');
INSERT INTO _tmdl_m_steps VALUES ('oakhaven template', 'sql_dim_customer', 1, 'Source', 'Source Ingestion', '"SELECT DISTINCT 
    c.customer_id');
INSERT INTO _tmdl_columns VALUES ('oakhaven template', 'sql_dim_customer', 'sql_dim_customer', 'string', 'none', 'sql_dim_customer', 'Attribute column representing sql_dim_customer.');
CREATE TABLE IF NOT EXISTS tmdl_oakhaven_template_sql_dim_customer (
    sql_dim_customer TEXT
);

INSERT OR REPLACE INTO _tmdl_tables VALUES ('oakhaven template', 'sql_dim_date', 'None');
INSERT INTO _tmdl_data_sources VALUES ('oakhaven template', 'sql_dim_date', 'Relational SQL Source', 'project/oakhaven.db', 'Native SQL Pushdown');
INSERT INTO _tmdl_m_steps VALUES ('oakhaven template', 'sql_dim_date', 1, 'Source', 'Source Ingestion', '"SELECT DISTINCT 
    d.datekey');
INSERT INTO _tmdl_columns VALUES ('oakhaven template', 'sql_dim_date', 'sql_dim_date', 'string', 'none', 'sql_dim_date', 'Attribute column representing sql_dim_date.');
CREATE TABLE IF NOT EXISTS tmdl_oakhaven_template_sql_dim_date (
    sql_dim_date TEXT
);

INSERT OR REPLACE INTO _tmdl_tables VALUES ('oakhaven template', 'sql_dim_employee', 'None');
INSERT INTO _tmdl_data_sources VALUES ('oakhaven template', 'sql_dim_employee', 'Relational SQL Source', 'project/oakhaven.db', 'Native SQL Pushdown');
INSERT INTO _tmdl_m_steps VALUES ('oakhaven template', 'sql_dim_employee', 1, 'Source', 'Source Ingestion', '"SELECT DISTINCT 
    e.employee_id');
INSERT INTO _tmdl_columns VALUES ('oakhaven template', 'sql_dim_employee', 'sql_dim_employee', 'string', 'none', 'sql_dim_employee', 'Attribute column representing sql_dim_employee.');
CREATE TABLE IF NOT EXISTS tmdl_oakhaven_template_sql_dim_employee (
    sql_dim_employee TEXT
);

INSERT OR REPLACE INTO _tmdl_tables VALUES ('oakhaven template', 'sql_dim_product', 'None');
INSERT INTO _tmdl_data_sources VALUES ('oakhaven template', 'sql_dim_product', 'Relational SQL Source', 'project/oakhaven.db', 'Native SQL Pushdown');
INSERT INTO _tmdl_m_steps VALUES ('oakhaven template', 'sql_dim_product', 1, 'Source', 'Source Ingestion', '"SELECT DISTINCT 
    p.product_id');
INSERT INTO _tmdl_columns VALUES ('oakhaven template', 'sql_dim_product', 'sql_dim_product', 'string', 'none', 'sql_dim_product', 'Attribute column representing sql_dim_product.');
CREATE TABLE IF NOT EXISTS tmdl_oakhaven_template_sql_dim_product (
    sql_dim_product TEXT
);

INSERT OR REPLACE INTO _tmdl_tables VALUES ('oakhaven template', 'sql_fact_sales', 'None');
INSERT INTO _tmdl_data_sources VALUES ('oakhaven template', 'sql_fact_sales', 'Relational SQL Source', 'project/oakhaven.db', 'Native SQL Pushdown');
INSERT INTO _tmdl_m_steps VALUES ('oakhaven template', 'sql_fact_sales', 1, 'Source', 'Source Ingestion', '"SELECT 
    f.order_id');
INSERT INTO _tmdl_columns VALUES ('oakhaven template', 'sql_fact_sales', 'sql_fact_sales', 'string', 'none', 'sql_fact_sales', 'Attribute column representing sql_fact_sales.');
CREATE TABLE IF NOT EXISTS tmdl_oakhaven_template_sql_fact_sales (
    sql_fact_sales TEXT
);

INSERT OR REPLACE INTO _tmdl_tables VALUES ('oakhaven template', 'sql_flat_sales_all', 'None');
INSERT INTO _tmdl_data_sources VALUES ('oakhaven template', 'sql_flat_sales_all', 'Relational SQL Source', 'project/oakhaven.db', 'Native SQL Pushdown');
INSERT INTO _tmdl_m_steps VALUES ('oakhaven template', 'sql_flat_sales_all', 1, 'Source', 'Source Ingestion', '"SELECT 
    f.order_id');
INSERT INTO _tmdl_m_steps VALUES ('oakhaven template', 'sql_flat_sales_all', 2, 'customer_id', 'Source Ingestion', 'c.customer_id
LEFT JOIN dim_product p ON f.product_id = p.product_id
LEFT JOIN dim_employee e ON f.e...');
INSERT INTO _tmdl_columns VALUES ('oakhaven template', 'sql_flat_sales_all', 'sql_flat_sales_all', 'string', 'none', 'sql_flat_sales_all', 'Attribute column representing sql_flat_sales_all.');
CREATE TABLE IF NOT EXISTS tmdl_oakhaven_template_sql_flat_sales_all (
    sql_flat_sales_all TEXT
);

INSERT OR REPLACE INTO _tmdl_tables VALUES ('oakhaven template', 'sql_flat_sales_completed', 'None');
INSERT INTO _tmdl_data_sources VALUES ('oakhaven template', 'sql_flat_sales_completed', 'Relational SQL Source', 'project/oakhaven.db', 'Native SQL Pushdown');
INSERT INTO _tmdl_m_steps VALUES ('oakhaven template', 'sql_flat_sales_completed', 1, 'Source', 'Source Ingestion', '"SELECT 
    f.order_id');
INSERT INTO _tmdl_m_steps VALUES ('oakhaven template', 'sql_flat_sales_completed', 2, 'customer_id', 'Filter Transformation', 'c.customer_id
LEFT JOIN dim_product p ON f.product_id = p.product_id
WHERE f.order_status = ''Complet...');
INSERT INTO _tmdl_columns VALUES ('oakhaven template', 'sql_flat_sales_completed', 'sql_flat_sales_completed', 'string', 'none', 'sql_flat_sales_completed', 'Attribute column representing sql_flat_sales_completed.');
CREATE TABLE IF NOT EXISTS tmdl_oakhaven_template_sql_flat_sales_completed (
    sql_flat_sales_completed TEXT
);
