-- =============================================================================

-- AUTOMATICALLY EXTRACTED VIEWS FROM POWER BI PROJECT (.PBIP / TMDL) METADATA

-- Generated by: pbip_poc/tools/pbip_to_db.py

-- Purpose: Push presentation/semantic layer queries back into database views.

-- =============================================================================



-- Source: duplicated oakhaven template/duplicated oakhaven template.SemanticModel/TMDLScripts/Script 1.tmdl
CREATE VIEW IF NOT EXISTS duplicated_oakhaven_template_script_1 AS
SELECT 
    f.order_id,
    f.order_line_id,
    f.customer_id,
    f.product_id,
    f.employee_id,
    f.datekey,
    f.quantity,
    f.unit_price,
    f.discount_pct,
    f.net_amount,
    f.payment_method,
    f.order_status,
    f.channel
FROM fact_sales f
ORDER BY f.order_date DESC, f.order_id, f.order_line_id
LIMIT 100;

-- Source: duplicated oakhaven template/duplicated oakhaven template.SemanticModel/definition/tables/dim_calendar.tmdl
CREATE VIEW IF NOT EXISTS duplicated_oakhaven_template_dim_calendar AS
SELECT DISTINCT 
    d.datekey,
    d.date,
    d.year,
    d.month,
    d.month_name,
    d.quarter,
    d.day_name,
    d.is_weekend
FROM dim_date d
WHERE d.datekey IN (
    SELECT datekey 
    FROM fact_sales 
    ORDER BY order_date DESC, order_id, order_line_id 
    LIMIT 100
);

-- Source: duplicated oakhaven template/duplicated oakhaven template.SemanticModel/definition/tables/dim_customer.tmdl
CREATE VIEW IF NOT EXISTS duplicated_oakhaven_template_dim_customer AS
SELECT DISTINCT 
    c.customer_id,
    c.full_name,
    c.email,
    c.state,
    c.customer_segment
FROM dim_customer c
WHERE c.customer_id IN (
    SELECT customer_id 
    FROM fact_sales 
    ORDER BY order_date DESC, order_id, order_line_id 
    LIMIT 100
);

-- Source: duplicated oakhaven template/duplicated oakhaven template.SemanticModel/definition/tables/dim_employee.tmdl
CREATE VIEW IF NOT EXISTS duplicated_oakhaven_template_dim_employee AS
SELECT DISTINCT 
    e.employee_id,
    e.full_name,
    e.department,
    e.region
FROM dim_employee e
WHERE e.employee_id IN (
    SELECT employee_id 
    FROM fact_sales 
    ORDER BY order_date DESC, order_id, order_line_id 
    LIMIT 100
);

-- Source: duplicated oakhaven template/duplicated oakhaven template.SemanticModel/definition/tables/fact_sales.tmdl
CREATE VIEW IF NOT EXISTS duplicated_oakhaven_template_fact_sales AS
SELECT 
    f.order_id,
    f.order_line_id,
    f.customer_id,
    f.product_id,
    f.employee_id,
    f.datekey,
    f.quantity,
    f.unit_price,
    f.discount_pct,
    f.net_amount,
    f.payment_method,
    f.order_status,
    f.channel
FROM fact_sales f
ORDER BY f.order_date DESC, f.order_id, f.order_line_id
LIMIT 100;

-- Source: duplicated oakhaven template/duplicated oakhaven template.SemanticModel/definition/tables/flat_sales_all.tmdl
CREATE VIEW IF NOT EXISTS duplicated_oakhaven_template_flat_sales_all AS
SELECT f.order_id, f.order_line_id, f.order_date, c.full_name AS customer_name, p.product_name, p.category AS product_category,f.quantity, f.net_amount, f.channel FROM fact_sales f LEFT JOIN dim_customer c ON f.customer_id = c.customer_id LEFT JOIN dim_product p ON f.product_id = p.product_id WHERE f.order_status = 'Completed' ORDER BY f.order_date DESC LIMIT 100;

-- Source: duplicated oakhaven template/duplicated oakhaven template.SemanticModel/definition/tables/flat_sales_completed.tmdl
CREATE VIEW IF NOT EXISTS duplicated_oakhaven_template_flat_sales_completed AS
SELECT 
    f.order_id,
    f.order_line_id,
    f.order_date,
    c.full_name AS customer_name,
    p.product_name,
    p.category AS product_category,
    f.quantity,
    f.net_amount,
    f.channel
FROM fact_sales f
LEFT JOIN dim_customer c ON f.customer_id = c.customer_id
LEFT JOIN dim_product p ON f.product_id = p.product_id
WHERE f.order_status = 'Completed'
ORDER BY f.order_date DESC
LIMIT 100;

-- Source: duplicated oakhaven template/duplicated oakhaven template.SemanticModel/definition/tables/sql_dim_customer.tmdl
CREATE VIEW IF NOT EXISTS duplicated_oakhaven_template_sql_dim_customer AS
SELECT DISTINCT 
    c.customer_id,
    c.full_name,
    c.email,
    c.state,
    c.customer_segment
FROM dim_customer c
WHERE c.customer_id IN (
    SELECT customer_id 
    FROM fact_sales 
    ORDER BY order_date DESC, order_id, order_line_id 
    LIMIT 100
);

-- Source: duplicated oakhaven template/duplicated oakhaven template.SemanticModel/definition/tables/sql_dim_date.tmdl
CREATE VIEW IF NOT EXISTS duplicated_oakhaven_template_sql_dim_date AS
SELECT DISTINCT 
    d.datekey,
    d.date,
    d.year,
    d.month,
    d.month_name,
    d.quarter,
    d.day_name,
    d.is_weekend
FROM dim_date d
WHERE d.datekey IN (
    SELECT datekey 
    FROM fact_sales 
    ORDER BY order_date DESC, order_id, order_line_id 
    LIMIT 100
);

-- Source: duplicated oakhaven template/duplicated oakhaven template.SemanticModel/definition/tables/sql_dim_employee.tmdl
CREATE VIEW IF NOT EXISTS duplicated_oakhaven_template_sql_dim_employee AS
SELECT DISTINCT 
    e.employee_id,
    e.full_name,
    e.department,
    e.region
FROM dim_employee e
WHERE e.employee_id IN (
    SELECT employee_id 
    FROM fact_sales 
    ORDER BY order_date DESC, order_id, order_line_id 
    LIMIT 100
);

-- Source: duplicated oakhaven template/duplicated oakhaven template.SemanticModel/definition/tables/sql_dim_product.tmdl
CREATE VIEW IF NOT EXISTS duplicated_oakhaven_template_sql_dim_product AS
SELECT DISTINCT 
    p.product_id,
    p.product_name,
    p.category,
    p.subcategory,
    p.brand,
    p.unit_cost,
    p.unit_price
FROM dim_product p
WHERE p.product_id IN (
    SELECT product_id 
    FROM fact_sales 
    ORDER BY order_date DESC, order_id, order_line_id 
    LIMIT 100
);

-- Source: duplicated oakhaven template/duplicated oakhaven template.SemanticModel/definition/tables/sql_fact_sales.tmdl
CREATE VIEW IF NOT EXISTS duplicated_oakhaven_template_sql_fact_sales AS
SELECT 
    f.order_id,
    f.order_line_id,
    f.customer_id,
    f.product_id,
    f.employee_id,
    f.datekey,
    f.quantity,
    f.unit_price,
    f.discount_pct,
    f.net_amount,
    f.payment_method,
    f.order_status,
    f.channel
FROM fact_sales f
ORDER BY f.order_date DESC, f.order_id, f.order_line_id
LIMIT 100;

-- Source: duplicated oakhaven template/duplicated oakhaven template.SemanticModel/definition/tables/sql_flat_sales_all.tmdl
CREATE VIEW IF NOT EXISTS duplicated_oakhaven_template_sql_flat_sales_all AS
SELECT 
    f.order_id,
    f.order_line_id,
    f.order_date,
    c.full_name AS customer_name,
    c.customer_segment,
    c.state AS customer_state,
    p.product_name,
    p.category AS product_category,
    p.brand AS product_brand,
    e.full_name AS sales_rep_name,
    e.region AS sales_region,
    f.quantity,
    f.unit_price,
    f.discount_pct,
    -- Embedded Business Logic #1: Gross Revenue
    ROUND(f.quantity * f.unit_price, 2) AS gross_amount,
    -- Embedded Business Logic #2: Net Revenue
    f.net_amount,
    -- Embedded Business Logic #3: Categorical Bucketing
    CASE 
        WHEN f.discount_pct >= 0.20 THEN 'High Discount (20%+)'
        WHEN f.discount_pct > 0 THEN 'Standard Discount'
        ELSE 'Full Price'
    END AS discount_tier,
    f.payment_method,
    f.order_status,
    f.channel
FROM fact_sales f
LEFT JOIN dim_customer c ON f.customer_id = c.customer_id
LEFT JOIN dim_product p ON f.product_id = p.product_id
LEFT JOIN dim_employee e ON f.employee_id = e.employee_id
ORDER BY f.order_date DESC, f.order_id, f.order_line_id
LIMIT 100;

-- Source: duplicated oakhaven template/duplicated oakhaven template.SemanticModel/definition/tables/sql_flat_sales_completed.tmdl
CREATE VIEW IF NOT EXISTS duplicated_oakhaven_template_sql_flat_sales_completed AS
SELECT 
    f.order_id,
    f.order_line_id,
    f.order_date,
    c.full_name AS customer_name,
    p.product_name,
    p.category AS product_category,
    f.quantity,
    f.net_amount,
    f.channel
FROM fact_sales f
LEFT JOIN dim_customer c ON f.customer_id = c.customer_id
LEFT JOIN dim_product p ON f.product_id = p.product_id
WHERE f.order_status = 'Completed'
ORDER BY f.order_date DESC
LIMIT 100;

-- Source: flat_sales_all/flat_sales_all.SemanticModel/TMDLScripts/Script 1.tmdl
CREATE VIEW IF NOT EXISTS flat_sales_all_script_1 AS
SELECT 
    f.order_id,
    f.order_line_id,
    f.customer_id,
    f.product_id,
    f.employee_id,
    f.datekey,
    f.quantity,
    f.unit_price,
    f.discount_pct,
    f.net_amount,
    f.payment_method,
    f.order_status,
    f.channel
FROM fact_sales f
ORDER BY f.order_date DESC, f.order_id, f.order_line_id
LIMIT 100;

-- Source: flat_sales_all/flat_sales_all.SemanticModel/definition/tables/dim_calendar.tmdl
CREATE VIEW IF NOT EXISTS flat_sales_all_dim_calendar AS
SELECT DISTINCT 
    d.datekey,
    d.date,
    d.year,
    d.month,
    d.month_name,
    d.quarter,
    d.day_name,
    d.is_weekend
FROM dim_date d
WHERE d.datekey IN (
    SELECT datekey 
    FROM fact_sales 
    ORDER BY order_date DESC, order_id, order_line_id 
    LIMIT 100
);

-- Source: flat_sales_all/flat_sales_all.SemanticModel/definition/tables/dim_employee.tmdl
CREATE VIEW IF NOT EXISTS flat_sales_all_dim_employee AS
SELECT DISTINCT 
    e.employee_id,
    e.full_name,
    e.department,
    e.region
FROM dim_employee e
WHERE e.employee_id IN (
    SELECT employee_id 
    FROM fact_sales 
    ORDER BY order_date DESC, order_id, order_line_id 
    LIMIT 100
);

-- Source: flat_sales_all/flat_sales_all.SemanticModel/definition/tables/fact_sales.tmdl
CREATE VIEW IF NOT EXISTS flat_sales_all_fact_sales AS
SELECT 
    f.order_id,
    f.order_line_id,
    f.customer_id,
    f.product_id,
    f.employee_id,
    f.datekey,
    f.quantity,
    f.unit_price,
    f.discount_pct,
    f.net_amount,
    f.payment_method,
    f.order_status,
    f.channel
FROM fact_sales f
ORDER BY f.order_date DESC, f.order_id, f.order_line_id
LIMIT 100;

-- Source: flat_sales_all/flat_sales_all.SemanticModel/definition/tables/flat_sales_all.tmdl
CREATE VIEW IF NOT EXISTS flat_sales_all_flat_sales_all AS
SELECT f.order_id, f.order_line_id, f.order_date, c.full_name AS customer_name, p.product_name, p.category AS product_category,f.quantity, f.net_amount, f.channel FROM fact_sales f LEFT JOIN dim_customer c ON f.customer_id = c.customer_id LEFT JOIN dim_product p ON f.product_id = p.product_id WHERE f.order_status = 'Completed' ORDER BY f.order_date DESC LIMIT 100;

-- Source: flat_sales_completed/flat_sales_completed.SemanticModel/TMDLScripts/Script 1.tmdl
CREATE VIEW IF NOT EXISTS flat_sales_completed_script_1 AS
SELECT 
    f.order_id,
    f.order_line_id,
    f.customer_id,
    f.product_id,
    f.employee_id,
    f.datekey,
    f.quantity,
    f.unit_price,
    f.discount_pct,
    f.net_amount,
    f.payment_method,
    f.order_status,
    f.channel
FROM fact_sales f
ORDER BY f.order_date DESC, f.order_id, f.order_line_id
LIMIT 100;

-- Source: flat_sales_completed/flat_sales_completed.SemanticModel/definition/tables/dim_calendar.tmdl
CREATE VIEW IF NOT EXISTS flat_sales_completed_dim_calendar AS
SELECT DISTINCT 
    d.datekey,
    d.date,
    d.year,
    d.month,
    d.month_name,
    d.quarter,
    d.day_name,
    d.is_weekend
FROM dim_date d
WHERE d.datekey IN (
    SELECT datekey 
    FROM fact_sales 
    ORDER BY order_date DESC, order_id, order_line_id 
    LIMIT 100
);

-- Source: flat_sales_completed/flat_sales_completed.SemanticModel/definition/tables/dim_customer.tmdl
CREATE VIEW IF NOT EXISTS flat_sales_completed_dim_customer AS
SELECT DISTINCT 
    c.customer_id,
    c.full_name,
    c.email,
    c.state,
    c.customer_segment
FROM dim_customer c
WHERE c.customer_id IN (
    SELECT customer_id 
    FROM fact_sales 
    ORDER BY order_date DESC, order_id, order_line_id 
    LIMIT 100
);

-- Source: flat_sales_completed/flat_sales_completed.SemanticModel/definition/tables/flat_sales_completed.tmdl
CREATE VIEW IF NOT EXISTS flat_sales_completed_flat_sales_completed AS
SELECT 
    f.order_id,
    f.order_line_id,
    f.order_date,
    c.full_name AS customer_name,
    p.product_name,
    p.category AS product_category,
    f.quantity,
    f.net_amount,
    f.channel
FROM fact_sales f
LEFT JOIN dim_customer c ON f.customer_id = c.customer_id
LEFT JOIN dim_product p ON f.product_id = p.product_id
WHERE f.order_status = 'Completed'
ORDER BY f.order_date DESC
LIMIT 100;

-- Source: flat_sales_completed/flat_sales_completed.SemanticModel/definition/tables/sql_dim_date.tmdl
CREATE VIEW IF NOT EXISTS flat_sales_completed_sql_dim_date AS
SELECT DISTINCT 
    d.datekey,
    d.date,
    d.year,
    d.month,
    d.month_name,
    d.quarter,
    d.day_name,
    d.is_weekend
FROM dim_date d
WHERE d.datekey IN (
    SELECT datekey 
    FROM fact_sales 
    ORDER BY order_date DESC, order_id, order_line_id 
    LIMIT 100
);

-- Source: flat_sales_completed/flat_sales_completed.SemanticModel/definition/tables/sql_dim_product.tmdl
CREATE VIEW IF NOT EXISTS flat_sales_completed_sql_dim_product AS
SELECT DISTINCT 
    p.product_id,
    p.product_name,
    p.category,
    p.subcategory,
    p.brand,
    p.unit_cost,
    p.unit_price
FROM dim_product p
WHERE p.product_id IN (
    SELECT product_id 
    FROM fact_sales 
    ORDER BY order_date DESC, order_id, order_line_id 
    LIMIT 100
);

-- Source: flat_sales_completed/flat_sales_completed.SemanticModel/definition/tables/sql_flat_sales_all.tmdl
CREATE VIEW IF NOT EXISTS flat_sales_completed_sql_flat_sales_all AS
SELECT 
    f.order_id,
    f.order_line_id,
    f.order_date,
    c.full_name AS customer_name,
    c.customer_segment,
    c.state AS customer_state,
    p.product_name,
    p.category AS product_category,
    p.brand AS product_brand,
    e.full_name AS sales_rep_name,
    e.region AS sales_region,
    f.quantity,
    f.unit_price,
    f.discount_pct,
    -- Embedded Business Logic #1: Gross Revenue
    ROUND(f.quantity * f.unit_price, 2) AS gross_amount,
    -- Embedded Business Logic #2: Net Revenue
    f.net_amount,
    -- Embedded Business Logic #3: Categorical Bucketing
    CASE 
        WHEN f.discount_pct >= 0.20 THEN 'High Discount (20%+)'
        WHEN f.discount_pct > 0 THEN 'Standard Discount'
        ELSE 'Full Price'
    END AS discount_tier,
    f.payment_method,
    f.order_status,
    f.channel
FROM fact_sales f
LEFT JOIN dim_customer c ON f.customer_id = c.customer_id
LEFT JOIN dim_product p ON f.product_id = p.product_id
LEFT JOIN dim_employee e ON f.employee_id = e.employee_id
ORDER BY f.order_date DESC, f.order_id, f.order_line_id
LIMIT 100;

-- Source: flat_sales_completed/flat_sales_completed.SemanticModel/definition/tables/sql_flat_sales_completed.tmdl
CREATE VIEW IF NOT EXISTS flat_sales_completed_sql_flat_sales_completed AS
SELECT 
    f.order_id,
    f.order_line_id,
    f.order_date,
    c.full_name AS customer_name,
    p.product_name,
    p.category AS product_category,
    f.quantity,
    f.net_amount,
    f.channel
FROM fact_sales f
LEFT JOIN dim_customer c ON f.customer_id = c.customer_id
LEFT JOIN dim_product p ON f.product_id = p.product_id
WHERE f.order_status = 'Completed'
ORDER BY f.order_date DESC
LIMIT 100;

-- Source: oakhaven template/oakhaven template.SemanticModel/TMDLScripts/Script 1.tmdl
CREATE VIEW IF NOT EXISTS oakhaven_template_script_1 AS
SELECT 
    f.order_id,
    f.order_line_id,
    f.customer_id,
    f.product_id,
    f.employee_id,
    f.datekey,
    f.quantity,
    f.unit_price,
    f.discount_pct,
    f.net_amount,
    f.payment_method,
    f.order_status,
    f.channel
FROM fact_sales f
ORDER BY f.order_date DESC, f.order_id, f.order_line_id
LIMIT 100;

-- Source: oakhaven template/oakhaven template.SemanticModel/definition/tables/dim_calendar.tmdl
CREATE VIEW IF NOT EXISTS oakhaven_template_dim_calendar AS
SELECT DISTINCT 
    d.datekey,
    d.date,
    d.year,
    d.month,
    d.month_name,
    d.quarter,
    d.day_name,
    d.is_weekend
FROM dim_date d
WHERE d.datekey IN (
    SELECT datekey 
    FROM fact_sales 
    ORDER BY order_date DESC, order_id, order_line_id 
    LIMIT 100
);

-- Source: oakhaven template/oakhaven template.SemanticModel/definition/tables/dim_customer.tmdl
CREATE VIEW IF NOT EXISTS oakhaven_template_dim_customer AS
SELECT DISTINCT 
    c.customer_id,
    c.full_name,
    c.email,
    c.state,
    c.customer_segment
FROM dim_customer c
WHERE c.customer_id IN (
    SELECT customer_id 
    FROM fact_sales 
    ORDER BY order_date DESC, order_id, order_line_id 
    LIMIT 100
);

-- Source: oakhaven template/oakhaven template.SemanticModel/definition/tables/dim_employee.tmdl
CREATE VIEW IF NOT EXISTS oakhaven_template_dim_employee AS
SELECT DISTINCT 
    e.employee_id,
    e.full_name,
    e.department,
    e.region
FROM dim_employee e
WHERE e.employee_id IN (
    SELECT employee_id 
    FROM fact_sales 
    ORDER BY order_date DESC, order_id, order_line_id 
    LIMIT 100
);

-- Source: oakhaven template/oakhaven template.SemanticModel/definition/tables/fact_sales.tmdl
CREATE VIEW IF NOT EXISTS oakhaven_template_fact_sales AS
SELECT 
    f.order_id,
    f.order_line_id,
    f.customer_id,
    f.product_id,
    f.employee_id,
    f.datekey,
    f.quantity,
    f.unit_price,
    f.discount_pct,
    f.net_amount,
    f.payment_method,
    f.order_status,
    f.channel
FROM fact_sales f
ORDER BY f.order_date DESC, f.order_id, f.order_line_id
LIMIT 100;

-- Source: oakhaven template/oakhaven template.SemanticModel/definition/tables/flat_sales_all.tmdl
CREATE VIEW IF NOT EXISTS oakhaven_template_flat_sales_all AS
SELECT f.order_id, f.order_line_id, f.order_date, c.full_name AS customer_name, p.product_name, p.category AS product_category,f.quantity, f.net_amount, f.channel FROM fact_sales f LEFT JOIN dim_customer c ON f.customer_id = c.customer_id LEFT JOIN dim_product p ON f.product_id = p.product_id WHERE f.order_status = 'Completed' ORDER BY f.order_date DESC LIMIT 100;

-- Source: oakhaven template/oakhaven template.SemanticModel/definition/tables/flat_sales_completed.tmdl
CREATE VIEW IF NOT EXISTS oakhaven_template_flat_sales_completed AS
SELECT 
    f.order_id,
    f.order_line_id,
    f.order_date,
    c.full_name AS customer_name,
    p.product_name,
    p.category AS product_category,
    f.quantity,
    f.net_amount,
    f.channel
FROM fact_sales f
LEFT JOIN dim_customer c ON f.customer_id = c.customer_id
LEFT JOIN dim_product p ON f.product_id = p.product_id
WHERE f.order_status = 'Completed'
ORDER BY f.order_date DESC
LIMIT 100;

-- Source: oakhaven template/oakhaven template.SemanticModel/definition/tables/sql_dim_customer.tmdl
CREATE VIEW IF NOT EXISTS oakhaven_template_sql_dim_customer AS
SELECT DISTINCT 
    c.customer_id,
    c.full_name,
    c.email,
    c.state,
    c.customer_segment
FROM dim_customer c
WHERE c.customer_id IN (
    SELECT customer_id 
    FROM fact_sales 
    ORDER BY order_date DESC, order_id, order_line_id 
    LIMIT 100
);

-- Source: oakhaven template/oakhaven template.SemanticModel/definition/tables/sql_dim_date.tmdl
CREATE VIEW IF NOT EXISTS oakhaven_template_sql_dim_date AS
SELECT DISTINCT 
    d.datekey,
    d.date,
    d.year,
    d.month,
    d.month_name,
    d.quarter,
    d.day_name,
    d.is_weekend
FROM dim_date d
WHERE d.datekey IN (
    SELECT datekey 
    FROM fact_sales 
    ORDER BY order_date DESC, order_id, order_line_id 
    LIMIT 100
);

-- Source: oakhaven template/oakhaven template.SemanticModel/definition/tables/sql_dim_employee.tmdl
CREATE VIEW IF NOT EXISTS oakhaven_template_sql_dim_employee AS
SELECT DISTINCT 
    e.employee_id,
    e.full_name,
    e.department,
    e.region
FROM dim_employee e
WHERE e.employee_id IN (
    SELECT employee_id 
    FROM fact_sales 
    ORDER BY order_date DESC, order_id, order_line_id 
    LIMIT 100
);

-- Source: oakhaven template/oakhaven template.SemanticModel/definition/tables/sql_dim_product.tmdl
CREATE VIEW IF NOT EXISTS oakhaven_template_sql_dim_product AS
SELECT DISTINCT 
    p.product_id,
    p.product_name,
    p.category,
    p.subcategory,
    p.brand,
    p.unit_cost,
    p.unit_price
FROM dim_product p
WHERE p.product_id IN (
    SELECT product_id 
    FROM fact_sales 
    ORDER BY order_date DESC, order_id, order_line_id 
    LIMIT 100
);

-- Source: oakhaven template/oakhaven template.SemanticModel/definition/tables/sql_fact_sales.tmdl
CREATE VIEW IF NOT EXISTS oakhaven_template_sql_fact_sales AS
SELECT 
    f.order_id,
    f.order_line_id,
    f.customer_id,
    f.product_id,
    f.employee_id,
    f.datekey,
    f.quantity,
    f.unit_price,
    f.discount_pct,
    f.net_amount,
    f.payment_method,
    f.order_status,
    f.channel
FROM fact_sales f
ORDER BY f.order_date DESC, f.order_id, f.order_line_id
LIMIT 100;

-- Source: oakhaven template/oakhaven template.SemanticModel/definition/tables/sql_flat_sales_all.tmdl
CREATE VIEW IF NOT EXISTS oakhaven_template_sql_flat_sales_all AS
SELECT 
    f.order_id,
    f.order_line_id,
    f.order_date,
    c.full_name AS customer_name,
    c.customer_segment,
    c.state AS customer_state,
    p.product_name,
    p.category AS product_category,
    p.brand AS product_brand,
    e.full_name AS sales_rep_name,
    e.region AS sales_region,
    f.quantity,
    f.unit_price,
    f.discount_pct,
    -- Embedded Business Logic #1: Gross Revenue
    ROUND(f.quantity * f.unit_price, 2) AS gross_amount,
    -- Embedded Business Logic #2: Net Revenue
    f.net_amount,
    -- Embedded Business Logic #3: Categorical Bucketing
    CASE 
        WHEN f.discount_pct >= 0.20 THEN 'High Discount (20%+)'
        WHEN f.discount_pct > 0 THEN 'Standard Discount'
        ELSE 'Full Price'
    END AS discount_tier,
    f.payment_method,
    f.order_status,
    f.channel
FROM fact_sales f
LEFT JOIN dim_customer c ON f.customer_id = c.customer_id
LEFT JOIN dim_product p ON f.product_id = p.product_id
LEFT JOIN dim_employee e ON f.employee_id = e.employee_id
ORDER BY f.order_date DESC, f.order_id, f.order_line_id
LIMIT 100;

-- Source: oakhaven template/oakhaven template.SemanticModel/definition/tables/sql_flat_sales_completed.tmdl
CREATE VIEW IF NOT EXISTS oakhaven_template_sql_flat_sales_completed AS
SELECT 
    f.order_id,
    f.order_line_id,
    f.order_date,
    c.full_name AS customer_name,
    p.product_name,
    p.category AS product_category,
    f.quantity,
    f.net_amount,
    f.channel
FROM fact_sales f
LEFT JOIN dim_customer c ON f.customer_id = c.customer_id
LEFT JOIN dim_product p ON f.product_id = p.product_id
WHERE f.order_status = 'Completed'
ORDER BY f.order_date DESC
LIMIT 100;