-- =============================================================================
-- AUTOMATICALLY GENERATED DDL & ENRICHED CATALOG FROM POWER BI TMDL METADATA
-- Generated by: pbip_poc/tools/parse_tmdl.py
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 1. ENRICHED DATABASE METADATA CATALOG TABLES WITH DESCRIPTIONS
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS _tmdl_projects (project_name TEXT PRIMARY KEY, table_count INT, relationship_count INT);
CREATE TABLE IF NOT EXISTS _tmdl_tables (project_name TEXT, table_name TEXT, lineage_tag TEXT, PRIMARY KEY (project_name, table_name));
CREATE TABLE IF NOT EXISTS _tmdl_columns (project_name TEXT, table_name TEXT, column_name TEXT, data_type TEXT, summarize_by TEXT, source_column TEXT, description TEXT);
CREATE TABLE IF NOT EXISTS _tmdl_measures (project_name TEXT, table_name TEXT, measure_name TEXT, expression TEXT, format_string TEXT, description TEXT);
CREATE TABLE IF NOT EXISTS _tmdl_relationships (project_name TEXT, rel_name TEXT, from_table TEXT, from_column TEXT, to_table TEXT, to_column TEXT, cardinality TEXT);

-- -----------------------------------------------------------------------------
-- PROJECT: duplicated oakhaven template
-- -----------------------------------------------------------------------------
INSERT OR REPLACE INTO _tmdl_projects VALUES ('duplicated oakhaven template', 13, 5);
INSERT INTO _tmdl_relationships VALUES ('duplicated oakhaven template', 'AutoDetected_1d28b393-7c5a-472e-8bdf-bbaefdfadc47', 'fact_sales', 'customer_id', 'dim_customer', 'customer_id', 'one');
INSERT INTO _tmdl_relationships VALUES ('duplicated oakhaven template', 'AutoDetected_de8de45f-ebb1-4d1d-a6b4-e19e17d854ac', 'fact_sales', 'datekey', 'dim_calendar', 'datekey', 'one');
INSERT INTO _tmdl_relationships VALUES ('duplicated oakhaven template', 'cdcabb57-8502-4d1c-1ca6-c29df34d8d3e', 'fact_sales', 'employee_id', 'dim_employee', 'employee_id', 'one');
INSERT INTO _tmdl_relationships VALUES ('duplicated oakhaven template', 'dab805ef-d296-87a4-acb2-347f07dc4199', 'flat_sales_all', 'order_date', 'dim_calendar', 'date', 'one');
INSERT INTO _tmdl_relationships VALUES ('duplicated oakhaven template', 'defc8ca4-33ee-19ab-d42b-240fcd45be3e', 'flat_sales_completed', 'order_date', 'dim_calendar', 'date', 'one');
INSERT OR REPLACE INTO _tmdl_tables VALUES ('duplicated oakhaven template', 'dim_calendar', '79ef8b5a-6d15-45c7-b623-d5bc95056c91');
INSERT INTO _tmdl_columns VALUES ('duplicated oakhaven template', 'dim_calendar', 'datekey', 'string', 'none', 'datekey', 'Integer surrogate key in YYYYMMDD format for date joins.');
INSERT INTO _tmdl_columns VALUES ('duplicated oakhaven template', 'dim_calendar', 'date', 'string', 'none', 'date', 'Standard ISO 8601 calendar date (YYYY-MM-DD).');
INSERT INTO _tmdl_columns VALUES ('duplicated oakhaven template', 'dim_calendar', 'year', 'string', 'none', 'year', 'Four-digit calendar year (e.g. 2026).');
INSERT INTO _tmdl_columns VALUES ('duplicated oakhaven template', 'dim_calendar', 'month', 'string', 'none', 'month', 'Numeric calendar month (1..12).');
INSERT INTO _tmdl_columns VALUES ('duplicated oakhaven template', 'dim_calendar', 'month_name', 'string', 'none', 'month_name', 'Full English month name (e.g. January, February).');
INSERT INTO _tmdl_columns VALUES ('duplicated oakhaven template', 'dim_calendar', 'quarter', 'string', 'none', 'quarter', 'Calendar quarter identifier (Q1, Q2, Q3, Q4).');
INSERT INTO _tmdl_columns VALUES ('duplicated oakhaven template', 'dim_calendar', 'day_name', 'string', 'none', 'day_name', 'Full English day name (e.g. Monday, Tuesday).');
INSERT INTO _tmdl_columns VALUES ('duplicated oakhaven template', 'dim_calendar', 'is_weekend', 'string', 'none', 'is_weekend', 'Boolean flag indicating Saturday or Sunday (1 = Weekend, 0 = Weekday).');
CREATE TABLE IF NOT EXISTS tmdl_duplicated_oakhaven_template_dim_calendar (
    datekey TEXT,
    date TEXT,
    year TEXT,
    month TEXT,
    month_name TEXT,
    quarter TEXT,
    day_name TEXT,
    is_weekend TEXT
);

INSERT OR REPLACE INTO _tmdl_tables VALUES ('duplicated oakhaven template', 'dim_customer', '1ace2605-f91c-4dba-a17c-16b7d1afa4b1');
INSERT INTO _tmdl_columns VALUES ('duplicated oakhaven template', 'dim_customer', 'customer_id', 'string', 'none', 'customer_id', 'Unique sequential identifier (1..600) for each customer.');
INSERT INTO _tmdl_columns VALUES ('duplicated oakhaven template', 'dim_customer', 'full_name', 'string', 'none', 'full_name', 'Concatenated customer full name (first + last).');
INSERT INTO _tmdl_columns VALUES ('duplicated oakhaven template', 'dim_customer', 'email', 'string', 'none', 'email', 'Primary email address associated with customer account.');
INSERT INTO _tmdl_columns VALUES ('duplicated oakhaven template', 'dim_customer', 'state', 'string', 'none', 'state', 'Customer geographic state or province code.');
INSERT INTO _tmdl_columns VALUES ('duplicated oakhaven template', 'dim_customer', 'customer_segment', 'string', 'none', 'customer_segment', 'Market segment classification (Retail, Wholesale, VIP).');
CREATE TABLE IF NOT EXISTS tmdl_duplicated_oakhaven_template_dim_customer (
    customer_id TEXT,
    full_name TEXT,
    email TEXT,
    state TEXT,
    customer_segment TEXT
);

INSERT OR REPLACE INTO _tmdl_tables VALUES ('duplicated oakhaven template', 'dim_employee', '43d7354d-c14a-4ab6-ac47-3e5506aec046');
INSERT INTO _tmdl_columns VALUES ('duplicated oakhaven template', 'dim_employee', 'employee_id', 'string', 'none', 'employee_id', 'Unique employee identification number (1..35).');
INSERT INTO _tmdl_columns VALUES ('duplicated oakhaven template', 'dim_employee', 'full_name', 'string', 'none', 'full_name', 'Concatenated customer full name (first + last).');
INSERT INTO _tmdl_columns VALUES ('duplicated oakhaven template', 'dim_employee', 'department', 'string', 'none', 'department', 'Company department (Sales, Support, Warehouse, Management).');
INSERT INTO _tmdl_columns VALUES ('duplicated oakhaven template', 'dim_employee', 'region', 'string', 'none', 'region', 'Assigned geographical sales territory (West, East, Central, South).');
CREATE TABLE IF NOT EXISTS tmdl_duplicated_oakhaven_template_dim_employee (
    employee_id TEXT,
    full_name TEXT,
    department TEXT,
    region TEXT
);

INSERT OR REPLACE INTO _tmdl_tables VALUES ('duplicated oakhaven template', 'fact_sales', 'a1840420-f3ab-469d-9219-ef364479ba4c');
INSERT INTO _tmdl_columns VALUES ('duplicated oakhaven template', 'fact_sales', 'order_id', 'string', 'none', 'order_id', 'Unique sales order transaction header identifier.');
INSERT INTO _tmdl_columns VALUES ('duplicated oakhaven template', 'fact_sales', 'order_line_id', 'string', 'none', 'order_line_id', 'Line item sequence number (1..N) within an order.');
INSERT INTO _tmdl_columns VALUES ('duplicated oakhaven template', 'fact_sales', 'customer_id', 'string', 'none', 'customer_id', 'Unique sequential identifier (1..600) for each customer.');
INSERT INTO _tmdl_columns VALUES ('duplicated oakhaven template', 'fact_sales', 'product_id', 'string', 'none', 'product_id', 'Unique surrogate key (1..150) identifying each merchandise item.');
INSERT INTO _tmdl_columns VALUES ('duplicated oakhaven template', 'fact_sales', 'employee_id', 'string', 'none', 'employee_id', 'Unique employee identification number (1..35).');
INSERT INTO _tmdl_columns VALUES ('duplicated oakhaven template', 'fact_sales', 'datekey', 'string', 'none', 'datekey', 'Integer surrogate key in YYYYMMDD format for date joins.');
INSERT INTO _tmdl_columns VALUES ('duplicated oakhaven template', 'fact_sales', 'quantity', 'string', 'none', 'quantity', 'Number of units purchased in order line.');
INSERT INTO _tmdl_columns VALUES ('duplicated oakhaven template', 'fact_sales', 'unit_price', 'string', 'none', 'unit_price', 'Retail selling price per unit ($) at time of order.');
INSERT INTO _tmdl_columns VALUES ('duplicated oakhaven template', 'fact_sales', 'discount_pct', 'string', 'none', 'discount_pct', 'Percentage discount applied (0.00 to 0.30).');
INSERT INTO _tmdl_columns VALUES ('duplicated oakhaven template', 'fact_sales', 'net_amount', 'string', 'none', 'net_amount', 'Actual net revenue earned after applying discounts.');
INSERT INTO _tmdl_columns VALUES ('duplicated oakhaven template', 'fact_sales', 'payment_method', 'string', 'none', 'payment_method', 'Payment tender channel (Credit Card, PayPal, Cash, Debit Card).');
INSERT INTO _tmdl_columns VALUES ('duplicated oakhaven template', 'fact_sales', 'order_status', 'string', 'none', 'order_status', 'Current status of transaction (Completed, Processing, Canceled, Returned).');
INSERT INTO _tmdl_columns VALUES ('duplicated oakhaven template', 'fact_sales', 'channel', 'string', 'none', 'channel', 'Sales channel origination (Web, Mobile App, In-Store Retail).');
CREATE TABLE IF NOT EXISTS tmdl_duplicated_oakhaven_template_fact_sales (
    order_id TEXT,
    order_line_id TEXT,
    customer_id TEXT,
    product_id TEXT,
    employee_id TEXT,
    datekey TEXT,
    quantity TEXT,
    unit_price TEXT,
    discount_pct TEXT,
    net_amount TEXT,
    payment_method TEXT,
    order_status TEXT,
    channel TEXT,
    FOREIGN KEY (customer_id) REFERENCES tmdl_duplicated_oakhaven_template_dim_customer(customer_id),
    FOREIGN KEY (datekey) REFERENCES tmdl_duplicated_oakhaven_template_dim_calendar(datekey),
    FOREIGN KEY (employee_id) REFERENCES tmdl_duplicated_oakhaven_template_dim_employee(employee_id)
);

INSERT OR REPLACE INTO _tmdl_tables VALUES ('duplicated oakhaven template', 'flat_sales_all', '3ead40b5-967c-42a6-8b3a-70b6eed40bea');
INSERT INTO _tmdl_columns VALUES ('duplicated oakhaven template', 'flat_sales_all', 'order_id', 'string', 'none', 'order_id', 'Unique sales order transaction header identifier.');
INSERT INTO _tmdl_columns VALUES ('duplicated oakhaven template', 'flat_sales_all', 'order_line_id', 'string', 'none', 'order_line_id', 'Line item sequence number (1..N) within an order.');
INSERT INTO _tmdl_columns VALUES ('duplicated oakhaven template', 'flat_sales_all', 'order_date', 'string', 'none', 'order_date', 'Transaction date on which order was placed.');
INSERT INTO _tmdl_columns VALUES ('duplicated oakhaven template', 'flat_sales_all', 'customer_name', 'string', 'none', 'customer_name', 'Full name of the purchasing customer.');
INSERT INTO _tmdl_columns VALUES ('duplicated oakhaven template', 'flat_sales_all', 'product_name', 'string', 'none', 'product_name', 'Catalog description and product title.');
INSERT INTO _tmdl_columns VALUES ('duplicated oakhaven template', 'flat_sales_all', 'product_category', 'string', 'none', 'product_category', 'Merchandise category of the ordered item.');
INSERT INTO _tmdl_columns VALUES ('duplicated oakhaven template', 'flat_sales_all', 'quantity', 'string', 'none', 'quantity', 'Number of units purchased in order line.');
INSERT INTO _tmdl_columns VALUES ('duplicated oakhaven template', 'flat_sales_all', 'net_amount', 'string', 'none', 'net_amount', 'Actual net revenue earned after applying discounts.');
INSERT INTO _tmdl_columns VALUES ('duplicated oakhaven template', 'flat_sales_all', 'channel', 'string', 'none', 'channel', 'Sales channel origination (Web, Mobile App, In-Store Retail).');
CREATE TABLE IF NOT EXISTS tmdl_duplicated_oakhaven_template_flat_sales_all (
    order_id TEXT,
    order_line_id TEXT,
    order_date TEXT,
    customer_name TEXT,
    product_name TEXT,
    product_category TEXT,
    quantity TEXT,
    net_amount TEXT,
    channel TEXT,
    FOREIGN KEY (order_date) REFERENCES tmdl_duplicated_oakhaven_template_dim_calendar(date)
);

INSERT OR REPLACE INTO _tmdl_tables VALUES ('duplicated oakhaven template', 'flat_sales_completed', 'b6be6beb-29f1-48a5-81c0-625157189e89');
INSERT INTO _tmdl_columns VALUES ('duplicated oakhaven template', 'flat_sales_completed', 'order_id', 'string', 'none', 'order_id', 'Unique sales order transaction header identifier.');
INSERT INTO _tmdl_columns VALUES ('duplicated oakhaven template', 'flat_sales_completed', 'order_line_id', 'string', 'none', 'order_line_id', 'Line item sequence number (1..N) within an order.');
INSERT INTO _tmdl_columns VALUES ('duplicated oakhaven template', 'flat_sales_completed', 'order_date', 'string', 'none', 'order_date', 'Transaction date on which order was placed.');
INSERT INTO _tmdl_columns VALUES ('duplicated oakhaven template', 'flat_sales_completed', 'customer_name', 'string', 'none', 'customer_name', 'Full name of the purchasing customer.');
INSERT INTO _tmdl_columns VALUES ('duplicated oakhaven template', 'flat_sales_completed', 'product_name', 'string', 'none', 'product_name', 'Catalog description and product title.');
INSERT INTO _tmdl_columns VALUES ('duplicated oakhaven template', 'flat_sales_completed', 'product_category', 'string', 'none', 'product_category', 'Merchandise category of the ordered item.');
INSERT INTO _tmdl_columns VALUES ('duplicated oakhaven template', 'flat_sales_completed', 'quantity', 'string', 'none', 'quantity', 'Number of units purchased in order line.');
INSERT INTO _tmdl_columns VALUES ('duplicated oakhaven template', 'flat_sales_completed', 'net_amount', 'string', 'none', 'net_amount', 'Actual net revenue earned after applying discounts.');
INSERT INTO _tmdl_columns VALUES ('duplicated oakhaven template', 'flat_sales_completed', 'channel', 'string', 'none', 'channel', 'Sales channel origination (Web, Mobile App, In-Store Retail).');
CREATE TABLE IF NOT EXISTS tmdl_duplicated_oakhaven_template_flat_sales_completed (
    order_id TEXT,
    order_line_id TEXT,
    order_date TEXT,
    customer_name TEXT,
    product_name TEXT,
    product_category TEXT,
    quantity TEXT,
    net_amount TEXT,
    channel TEXT,
    FOREIGN KEY (order_date) REFERENCES tmdl_duplicated_oakhaven_template_dim_calendar(date)
);

INSERT OR REPLACE INTO _tmdl_tables VALUES ('duplicated oakhaven template', 'sql_dim_customer', '60157a56-9e5c-44e3-afe2-a1d8596c4810');
INSERT INTO _tmdl_columns VALUES ('duplicated oakhaven template', 'sql_dim_customer', 'sql_dim_customer', 'string', 'none', 'sql_dim_customer', 'Attribute column representing sql_dim_customer.');
CREATE TABLE IF NOT EXISTS tmdl_duplicated_oakhaven_template_sql_dim_customer (
    sql_dim_customer TEXT
);

INSERT OR REPLACE INTO _tmdl_tables VALUES ('duplicated oakhaven template', 'sql_dim_date', 'e90299e8-e196-4d64-af85-6922f6c9c57b');
INSERT INTO _tmdl_columns VALUES ('duplicated oakhaven template', 'sql_dim_date', 'sql_dim_date', 'string', 'none', 'sql_dim_date', 'Attribute column representing sql_dim_date.');
CREATE TABLE IF NOT EXISTS tmdl_duplicated_oakhaven_template_sql_dim_date (
    sql_dim_date TEXT
);

INSERT OR REPLACE INTO _tmdl_tables VALUES ('duplicated oakhaven template', 'sql_dim_employee', '40290057-dafc-4a1a-b105-70828199df3c');
INSERT INTO _tmdl_columns VALUES ('duplicated oakhaven template', 'sql_dim_employee', 'sql_dim_employee', 'string', 'none', 'sql_dim_employee', 'Attribute column representing sql_dim_employee.');
CREATE TABLE IF NOT EXISTS tmdl_duplicated_oakhaven_template_sql_dim_employee (
    sql_dim_employee TEXT
);

INSERT OR REPLACE INTO _tmdl_tables VALUES ('duplicated oakhaven template', 'sql_dim_product', '5beec82b-4127-4513-be49-058477e6370a');
INSERT INTO _tmdl_columns VALUES ('duplicated oakhaven template', 'sql_dim_product', 'sql_dim_product', 'string', 'none', 'sql_dim_product', 'Attribute column representing sql_dim_product.');
CREATE TABLE IF NOT EXISTS tmdl_duplicated_oakhaven_template_sql_dim_product (
    sql_dim_product TEXT
);

INSERT OR REPLACE INTO _tmdl_tables VALUES ('duplicated oakhaven template', 'sql_fact_sales', '3aaa36e0-22c9-499d-8643-e01165b98cf4');
INSERT INTO _tmdl_columns VALUES ('duplicated oakhaven template', 'sql_fact_sales', 'sql_fact_sales', 'string', 'none', 'sql_fact_sales', 'Attribute column representing sql_fact_sales.');
CREATE TABLE IF NOT EXISTS tmdl_duplicated_oakhaven_template_sql_fact_sales (
    sql_fact_sales TEXT
);

INSERT OR REPLACE INTO _tmdl_tables VALUES ('duplicated oakhaven template', 'sql_flat_sales_all', 'efd15e42-7d83-4bca-b6a3-646d48ab884b');
INSERT INTO _tmdl_columns VALUES ('duplicated oakhaven template', 'sql_flat_sales_all', 'sql_flat_sales_all', 'string', 'none', 'sql_flat_sales_all', 'Attribute column representing sql_flat_sales_all.');
CREATE TABLE IF NOT EXISTS tmdl_duplicated_oakhaven_template_sql_flat_sales_all (
    sql_flat_sales_all TEXT
);

INSERT OR REPLACE INTO _tmdl_tables VALUES ('duplicated oakhaven template', 'sql_flat_sales_completed', '7751f11b-efde-485d-9bdc-b92557dcf54d');
INSERT INTO _tmdl_columns VALUES ('duplicated oakhaven template', 'sql_flat_sales_completed', 'sql_flat_sales_completed', 'string', 'none', 'sql_flat_sales_completed', 'Attribute column representing sql_flat_sales_completed.');
CREATE TABLE IF NOT EXISTS tmdl_duplicated_oakhaven_template_sql_flat_sales_completed (
    sql_flat_sales_completed TEXT
);

-- -----------------------------------------------------------------------------
-- PROJECT: flat_sales_all
-- -----------------------------------------------------------------------------
INSERT OR REPLACE INTO _tmdl_projects VALUES ('flat_sales_all', 4, 4);
INSERT INTO _tmdl_relationships VALUES ('flat_sales_all', 'AutoDetected_de8de45f-ebb1-4d1d-a6b4-e19e17d854ac', 'fact_sales', 'datekey', 'dim_calendar', 'datekey', 'one');
INSERT INTO _tmdl_relationships VALUES ('flat_sales_all', 'cdcabb57-8502-4d1c-1ca6-c29df34d8d3e', 'fact_sales', 'employee_id', 'dim_employee', 'employee_id', 'one');
INSERT INTO _tmdl_relationships VALUES ('flat_sales_all', 'dab805ef-d296-87a4-acb2-347f07dc4199', 'flat_sales_all', 'order_date', 'dim_calendar', 'date', 'one');
INSERT INTO _tmdl_relationships VALUES ('flat_sales_all', '8defae2f-1aaf-a630-18a1-4f48a16e650a', 'fact_sales', 'order_id', 'flat_sales_all', 'order_id', 'many');
INSERT OR REPLACE INTO _tmdl_tables VALUES ('flat_sales_all', 'dim_calendar', '79ef8b5a-6d15-45c7-b623-d5bc95056c91');
INSERT INTO _tmdl_columns VALUES ('flat_sales_all', 'dim_calendar', 'datekey', 'string', 'none', 'datekey', 'Integer surrogate key in YYYYMMDD format for date joins.');
INSERT INTO _tmdl_columns VALUES ('flat_sales_all', 'dim_calendar', 'date', 'string', 'none', 'date', 'Standard ISO 8601 calendar date (YYYY-MM-DD).');
INSERT INTO _tmdl_columns VALUES ('flat_sales_all', 'dim_calendar', 'year', 'string', 'none', 'year', 'Four-digit calendar year (e.g. 2026).');
INSERT INTO _tmdl_columns VALUES ('flat_sales_all', 'dim_calendar', 'month', 'string', 'none', 'month', 'Numeric calendar month (1..12).');
INSERT INTO _tmdl_columns VALUES ('flat_sales_all', 'dim_calendar', 'month_name', 'string', 'none', 'month_name', 'Full English month name (e.g. January, February).');
INSERT INTO _tmdl_columns VALUES ('flat_sales_all', 'dim_calendar', 'quarter', 'string', 'none', 'quarter', 'Calendar quarter identifier (Q1, Q2, Q3, Q4).');
INSERT INTO _tmdl_columns VALUES ('flat_sales_all', 'dim_calendar', 'day_name', 'string', 'none', 'day_name', 'Full English day name (e.g. Monday, Tuesday).');
INSERT INTO _tmdl_columns VALUES ('flat_sales_all', 'dim_calendar', 'is_weekend', 'string', 'none', 'is_weekend', 'Boolean flag indicating Saturday or Sunday (1 = Weekend, 0 = Weekday).');
CREATE TABLE IF NOT EXISTS tmdl_flat_sales_all_dim_calendar (
    datekey TEXT,
    date TEXT,
    year TEXT,
    month TEXT,
    month_name TEXT,
    quarter TEXT,
    day_name TEXT,
    is_weekend TEXT
);

INSERT OR REPLACE INTO _tmdl_tables VALUES ('flat_sales_all', 'dim_employee', '43d7354d-c14a-4ab6-ac47-3e5506aec046');
INSERT INTO _tmdl_columns VALUES ('flat_sales_all', 'dim_employee', 'employee_id', 'string', 'none', 'employee_id', 'Unique employee identification number (1..35).');
INSERT INTO _tmdl_columns VALUES ('flat_sales_all', 'dim_employee', 'full_name', 'string', 'none', 'full_name', 'Concatenated customer full name (first + last).');
INSERT INTO _tmdl_columns VALUES ('flat_sales_all', 'dim_employee', 'department', 'string', 'none', 'department', 'Company department (Sales, Support, Warehouse, Management).');
INSERT INTO _tmdl_columns VALUES ('flat_sales_all', 'dim_employee', 'region', 'string', 'none', 'region', 'Assigned geographical sales territory (West, East, Central, South).');
CREATE TABLE IF NOT EXISTS tmdl_flat_sales_all_dim_employee (
    employee_id TEXT,
    full_name TEXT,
    department TEXT,
    region TEXT
);

INSERT OR REPLACE INTO _tmdl_tables VALUES ('flat_sales_all', 'fact_sales', 'a1840420-f3ab-469d-9219-ef364479ba4c');
INSERT INTO _tmdl_columns VALUES ('flat_sales_all', 'fact_sales', 'order_id', 'string', 'none', 'order_id', 'Unique sales order transaction header identifier.');
INSERT INTO _tmdl_columns VALUES ('flat_sales_all', 'fact_sales', 'order_line_id', 'string', 'none', 'order_line_id', 'Line item sequence number (1..N) within an order.');
INSERT INTO _tmdl_columns VALUES ('flat_sales_all', 'fact_sales', 'customer_id', 'string', 'none', 'customer_id', 'Unique sequential identifier (1..600) for each customer.');
INSERT INTO _tmdl_columns VALUES ('flat_sales_all', 'fact_sales', 'product_id', 'string', 'none', 'product_id', 'Unique surrogate key (1..150) identifying each merchandise item.');
INSERT INTO _tmdl_columns VALUES ('flat_sales_all', 'fact_sales', 'employee_id', 'string', 'none', 'employee_id', 'Unique employee identification number (1..35).');
INSERT INTO _tmdl_columns VALUES ('flat_sales_all', 'fact_sales', 'datekey', 'string', 'none', 'datekey', 'Integer surrogate key in YYYYMMDD format for date joins.');
INSERT INTO _tmdl_columns VALUES ('flat_sales_all', 'fact_sales', 'quantity', 'string', 'none', 'quantity', 'Number of units purchased in order line.');
INSERT INTO _tmdl_columns VALUES ('flat_sales_all', 'fact_sales', 'unit_price', 'string', 'none', 'unit_price', 'Retail selling price per unit ($) at time of order.');
INSERT INTO _tmdl_columns VALUES ('flat_sales_all', 'fact_sales', 'discount_pct', 'string', 'none', 'discount_pct', 'Percentage discount applied (0.00 to 0.30).');
INSERT INTO _tmdl_columns VALUES ('flat_sales_all', 'fact_sales', 'net_amount', 'string', 'none', 'net_amount', 'Actual net revenue earned after applying discounts.');
INSERT INTO _tmdl_columns VALUES ('flat_sales_all', 'fact_sales', 'payment_method', 'string', 'none', 'payment_method', 'Payment tender channel (Credit Card, PayPal, Cash, Debit Card).');
INSERT INTO _tmdl_columns VALUES ('flat_sales_all', 'fact_sales', 'order_status', 'string', 'none', 'order_status', 'Current status of transaction (Completed, Processing, Canceled, Returned).');
INSERT INTO _tmdl_columns VALUES ('flat_sales_all', 'fact_sales', 'channel', 'string', 'none', 'channel', 'Sales channel origination (Web, Mobile App, In-Store Retail).');
CREATE TABLE IF NOT EXISTS tmdl_flat_sales_all_fact_sales (
    order_id TEXT,
    order_line_id TEXT,
    customer_id TEXT,
    product_id TEXT,
    employee_id TEXT,
    datekey TEXT,
    quantity TEXT,
    unit_price TEXT,
    discount_pct TEXT,
    net_amount TEXT,
    payment_method TEXT,
    order_status TEXT,
    channel TEXT,
    FOREIGN KEY (datekey) REFERENCES tmdl_flat_sales_all_dim_calendar(datekey),
    FOREIGN KEY (employee_id) REFERENCES tmdl_flat_sales_all_dim_employee(employee_id),
    FOREIGN KEY (order_id) REFERENCES tmdl_flat_sales_all_flat_sales_all(order_id)
);

INSERT OR REPLACE INTO _tmdl_tables VALUES ('flat_sales_all', 'flat_sales_all', '3ead40b5-967c-42a6-8b3a-70b6eed40bea');
INSERT INTO _tmdl_columns VALUES ('flat_sales_all', 'flat_sales_all', 'order_id', 'string', 'none', 'order_id', 'Unique sales order transaction header identifier.');
INSERT INTO _tmdl_columns VALUES ('flat_sales_all', 'flat_sales_all', 'order_line_id', 'string', 'none', 'order_line_id', 'Line item sequence number (1..N) within an order.');
INSERT INTO _tmdl_columns VALUES ('flat_sales_all', 'flat_sales_all', 'order_date', 'string', 'none', 'order_date', 'Transaction date on which order was placed.');
INSERT INTO _tmdl_columns VALUES ('flat_sales_all', 'flat_sales_all', 'customer_name', 'string', 'none', 'customer_name', 'Full name of the purchasing customer.');
INSERT INTO _tmdl_columns VALUES ('flat_sales_all', 'flat_sales_all', 'product_name', 'string', 'none', 'product_name', 'Catalog description and product title.');
INSERT INTO _tmdl_columns VALUES ('flat_sales_all', 'flat_sales_all', 'product_category', 'string', 'none', 'product_category', 'Merchandise category of the ordered item.');
INSERT INTO _tmdl_columns VALUES ('flat_sales_all', 'flat_sales_all', 'quantity', 'string', 'none', 'quantity', 'Number of units purchased in order line.');
INSERT INTO _tmdl_columns VALUES ('flat_sales_all', 'flat_sales_all', 'net_amount', 'string', 'none', 'net_amount', 'Actual net revenue earned after applying discounts.');
INSERT INTO _tmdl_columns VALUES ('flat_sales_all', 'flat_sales_all', 'channel', 'string', 'none', 'channel', 'Sales channel origination (Web, Mobile App, In-Store Retail).');
CREATE TABLE IF NOT EXISTS tmdl_flat_sales_all_flat_sales_all (
    order_id TEXT,
    order_line_id TEXT,
    order_date TEXT,
    customer_name TEXT,
    product_name TEXT,
    product_category TEXT,
    quantity TEXT,
    net_amount TEXT,
    channel TEXT,
    FOREIGN KEY (order_date) REFERENCES tmdl_flat_sales_all_dim_calendar(date)
);

-- -----------------------------------------------------------------------------
-- PROJECT: flat_sales_completed
-- -----------------------------------------------------------------------------
INSERT OR REPLACE INTO _tmdl_projects VALUES ('flat_sales_completed', 7, 1);
INSERT INTO _tmdl_relationships VALUES ('flat_sales_completed', 'defc8ca4-33ee-19ab-d42b-240fcd45be3e', 'flat_sales_completed', 'order_date', 'dim_calendar', 'date', 'one');
INSERT OR REPLACE INTO _tmdl_tables VALUES ('flat_sales_completed', 'dim_calendar', '79ef8b5a-6d15-45c7-b623-d5bc95056c91');
INSERT INTO _tmdl_columns VALUES ('flat_sales_completed', 'dim_calendar', 'datekey', 'string', 'none', 'datekey', 'Integer surrogate key in YYYYMMDD format for date joins.');
INSERT INTO _tmdl_columns VALUES ('flat_sales_completed', 'dim_calendar', 'date', 'string', 'none', 'date', 'Standard ISO 8601 calendar date (YYYY-MM-DD).');
INSERT INTO _tmdl_columns VALUES ('flat_sales_completed', 'dim_calendar', 'year', 'string', 'none', 'year', 'Four-digit calendar year (e.g. 2026).');
INSERT INTO _tmdl_columns VALUES ('flat_sales_completed', 'dim_calendar', 'month', 'string', 'none', 'month', 'Numeric calendar month (1..12).');
INSERT INTO _tmdl_columns VALUES ('flat_sales_completed', 'dim_calendar', 'month_name', 'string', 'none', 'month_name', 'Full English month name (e.g. January, February).');
INSERT INTO _tmdl_columns VALUES ('flat_sales_completed', 'dim_calendar', 'quarter', 'string', 'none', 'quarter', 'Calendar quarter identifier (Q1, Q2, Q3, Q4).');
INSERT INTO _tmdl_columns VALUES ('flat_sales_completed', 'dim_calendar', 'day_name', 'string', 'none', 'day_name', 'Full English day name (e.g. Monday, Tuesday).');
INSERT INTO _tmdl_columns VALUES ('flat_sales_completed', 'dim_calendar', 'is_weekend', 'string', 'none', 'is_weekend', 'Boolean flag indicating Saturday or Sunday (1 = Weekend, 0 = Weekday).');
CREATE TABLE IF NOT EXISTS tmdl_flat_sales_completed_dim_calendar (
    datekey TEXT,
    date TEXT,
    year TEXT,
    month TEXT,
    month_name TEXT,
    quarter TEXT,
    day_name TEXT,
    is_weekend TEXT
);

INSERT OR REPLACE INTO _tmdl_tables VALUES ('flat_sales_completed', 'dim_customer', '1ace2605-f91c-4dba-a17c-16b7d1afa4b1');
INSERT INTO _tmdl_columns VALUES ('flat_sales_completed', 'dim_customer', 'customer_id', 'string', 'none', 'customer_id', 'Unique sequential identifier (1..600) for each customer.');
INSERT INTO _tmdl_columns VALUES ('flat_sales_completed', 'dim_customer', 'full_name', 'string', 'none', 'full_name', 'Concatenated customer full name (first + last).');
INSERT INTO _tmdl_columns VALUES ('flat_sales_completed', 'dim_customer', 'email', 'string', 'none', 'email', 'Primary email address associated with customer account.');
INSERT INTO _tmdl_columns VALUES ('flat_sales_completed', 'dim_customer', 'state', 'string', 'none', 'state', 'Customer geographic state or province code.');
INSERT INTO _tmdl_columns VALUES ('flat_sales_completed', 'dim_customer', 'customer_segment', 'string', 'none', 'customer_segment', 'Market segment classification (Retail, Wholesale, VIP).');
CREATE TABLE IF NOT EXISTS tmdl_flat_sales_completed_dim_customer (
    customer_id TEXT,
    full_name TEXT,
    email TEXT,
    state TEXT,
    customer_segment TEXT
);

INSERT OR REPLACE INTO _tmdl_tables VALUES ('flat_sales_completed', 'flat_sales_completed', 'b6be6beb-29f1-48a5-81c0-625157189e89');
INSERT INTO _tmdl_columns VALUES ('flat_sales_completed', 'flat_sales_completed', 'order_id', 'string', 'none', 'order_id', 'Unique sales order transaction header identifier.');
INSERT INTO _tmdl_columns VALUES ('flat_sales_completed', 'flat_sales_completed', 'order_line_id', 'string', 'none', 'order_line_id', 'Line item sequence number (1..N) within an order.');
INSERT INTO _tmdl_columns VALUES ('flat_sales_completed', 'flat_sales_completed', 'order_date', 'string', 'none', 'order_date', 'Transaction date on which order was placed.');
INSERT INTO _tmdl_columns VALUES ('flat_sales_completed', 'flat_sales_completed', 'customer_name', 'string', 'none', 'customer_name', 'Full name of the purchasing customer.');
INSERT INTO _tmdl_columns VALUES ('flat_sales_completed', 'flat_sales_completed', 'product_name', 'string', 'none', 'product_name', 'Catalog description and product title.');
INSERT INTO _tmdl_columns VALUES ('flat_sales_completed', 'flat_sales_completed', 'product_category', 'string', 'none', 'product_category', 'Merchandise category of the ordered item.');
INSERT INTO _tmdl_columns VALUES ('flat_sales_completed', 'flat_sales_completed', 'quantity', 'string', 'none', 'quantity', 'Number of units purchased in order line.');
INSERT INTO _tmdl_columns VALUES ('flat_sales_completed', 'flat_sales_completed', 'net_amount', 'string', 'none', 'net_amount', 'Actual net revenue earned after applying discounts.');
INSERT INTO _tmdl_columns VALUES ('flat_sales_completed', 'flat_sales_completed', 'channel', 'string', 'none', 'channel', 'Sales channel origination (Web, Mobile App, In-Store Retail).');
CREATE TABLE IF NOT EXISTS tmdl_flat_sales_completed_flat_sales_completed (
    order_id TEXT,
    order_line_id TEXT,
    order_date TEXT,
    customer_name TEXT,
    product_name TEXT,
    product_category TEXT,
    quantity TEXT,
    net_amount TEXT,
    channel TEXT,
    FOREIGN KEY (order_date) REFERENCES tmdl_flat_sales_completed_dim_calendar(date)
);

INSERT OR REPLACE INTO _tmdl_tables VALUES ('flat_sales_completed', 'sql_dim_date', 'e90299e8-e196-4d64-af85-6922f6c9c57b');
INSERT INTO _tmdl_columns VALUES ('flat_sales_completed', 'sql_dim_date', 'sql_dim_date', 'string', 'none', 'sql_dim_date', 'Attribute column representing sql_dim_date.');
CREATE TABLE IF NOT EXISTS tmdl_flat_sales_completed_sql_dim_date (
    sql_dim_date TEXT
);

INSERT OR REPLACE INTO _tmdl_tables VALUES ('flat_sales_completed', 'sql_dim_product', '5beec82b-4127-4513-be49-058477e6370a');
INSERT INTO _tmdl_columns VALUES ('flat_sales_completed', 'sql_dim_product', 'sql_dim_product', 'string', 'none', 'sql_dim_product', 'Attribute column representing sql_dim_product.');
CREATE TABLE IF NOT EXISTS tmdl_flat_sales_completed_sql_dim_product (
    sql_dim_product TEXT
);

INSERT OR REPLACE INTO _tmdl_tables VALUES ('flat_sales_completed', 'sql_flat_sales_all', 'efd15e42-7d83-4bca-b6a3-646d48ab884b');
INSERT INTO _tmdl_columns VALUES ('flat_sales_completed', 'sql_flat_sales_all', 'sql_flat_sales_all', 'string', 'none', 'sql_flat_sales_all', 'Attribute column representing sql_flat_sales_all.');
CREATE TABLE IF NOT EXISTS tmdl_flat_sales_completed_sql_flat_sales_all (
    sql_flat_sales_all TEXT
);

INSERT OR REPLACE INTO _tmdl_tables VALUES ('flat_sales_completed', 'sql_flat_sales_completed', '7751f11b-efde-485d-9bdc-b92557dcf54d');
INSERT INTO _tmdl_columns VALUES ('flat_sales_completed', 'sql_flat_sales_completed', 'sql_flat_sales_completed', 'string', 'none', 'sql_flat_sales_completed', 'Attribute column representing sql_flat_sales_completed.');
CREATE TABLE IF NOT EXISTS tmdl_flat_sales_completed_sql_flat_sales_completed (
    sql_flat_sales_completed TEXT
);

-- -----------------------------------------------------------------------------
-- PROJECT: oakhaven template
-- -----------------------------------------------------------------------------
INSERT OR REPLACE INTO _tmdl_projects VALUES ('oakhaven template', 13, 5);
INSERT INTO _tmdl_relationships VALUES ('oakhaven template', 'AutoDetected_1d28b393-7c5a-472e-8bdf-bbaefdfadc47', 'fact_sales', 'customer_id', 'dim_customer', 'customer_id', 'one');
INSERT INTO _tmdl_relationships VALUES ('oakhaven template', 'AutoDetected_de8de45f-ebb1-4d1d-a6b4-e19e17d854ac', 'fact_sales', 'datekey', 'dim_calendar', 'datekey', 'one');
INSERT INTO _tmdl_relationships VALUES ('oakhaven template', 'cdcabb57-8502-4d1c-1ca6-c29df34d8d3e', 'fact_sales', 'employee_id', 'dim_employee', 'employee_id', 'one');
INSERT INTO _tmdl_relationships VALUES ('oakhaven template', 'dab805ef-d296-87a4-acb2-347f07dc4199', 'flat_sales_all', 'order_date', 'dim_calendar', 'date', 'one');
INSERT INTO _tmdl_relationships VALUES ('oakhaven template', 'defc8ca4-33ee-19ab-d42b-240fcd45be3e', 'flat_sales_completed', 'order_date', 'dim_calendar', 'date', 'one');
INSERT OR REPLACE INTO _tmdl_tables VALUES ('oakhaven template', 'dim_calendar', '79ef8b5a-6d15-45c7-b623-d5bc95056c91');
INSERT INTO _tmdl_columns VALUES ('oakhaven template', 'dim_calendar', 'datekey', 'string', 'none', 'datekey', 'Integer surrogate key in YYYYMMDD format for date joins.');
INSERT INTO _tmdl_columns VALUES ('oakhaven template', 'dim_calendar', 'date', 'string', 'none', 'date', 'Standard ISO 8601 calendar date (YYYY-MM-DD).');
INSERT INTO _tmdl_columns VALUES ('oakhaven template', 'dim_calendar', 'year', 'string', 'none', 'year', 'Four-digit calendar year (e.g. 2026).');
INSERT INTO _tmdl_columns VALUES ('oakhaven template', 'dim_calendar', 'month', 'string', 'none', 'month', 'Numeric calendar month (1..12).');
INSERT INTO _tmdl_columns VALUES ('oakhaven template', 'dim_calendar', 'month_name', 'string', 'none', 'month_name', 'Full English month name (e.g. January, February).');
INSERT INTO _tmdl_columns VALUES ('oakhaven template', 'dim_calendar', 'quarter', 'string', 'none', 'quarter', 'Calendar quarter identifier (Q1, Q2, Q3, Q4).');
INSERT INTO _tmdl_columns VALUES ('oakhaven template', 'dim_calendar', 'day_name', 'string', 'none', 'day_name', 'Full English day name (e.g. Monday, Tuesday).');
INSERT INTO _tmdl_columns VALUES ('oakhaven template', 'dim_calendar', 'is_weekend', 'string', 'none', 'is_weekend', 'Boolean flag indicating Saturday or Sunday (1 = Weekend, 0 = Weekday).');
CREATE TABLE IF NOT EXISTS tmdl_oakhaven_template_dim_calendar (
    datekey TEXT,
    date TEXT,
    year TEXT,
    month TEXT,
    month_name TEXT,
    quarter TEXT,
    day_name TEXT,
    is_weekend TEXT
);

INSERT OR REPLACE INTO _tmdl_tables VALUES ('oakhaven template', 'dim_customer', '1ace2605-f91c-4dba-a17c-16b7d1afa4b1');
INSERT INTO _tmdl_columns VALUES ('oakhaven template', 'dim_customer', 'customer_id', 'string', 'none', 'customer_id', 'Unique sequential identifier (1..600) for each customer.');
INSERT INTO _tmdl_columns VALUES ('oakhaven template', 'dim_customer', 'full_name', 'string', 'none', 'full_name', 'Concatenated customer full name (first + last).');
INSERT INTO _tmdl_columns VALUES ('oakhaven template', 'dim_customer', 'email', 'string', 'none', 'email', 'Primary email address associated with customer account.');
INSERT INTO _tmdl_columns VALUES ('oakhaven template', 'dim_customer', 'state', 'string', 'none', 'state', 'Customer geographic state or province code.');
INSERT INTO _tmdl_columns VALUES ('oakhaven template', 'dim_customer', 'customer_segment', 'string', 'none', 'customer_segment', 'Market segment classification (Retail, Wholesale, VIP).');
CREATE TABLE IF NOT EXISTS tmdl_oakhaven_template_dim_customer (
    customer_id TEXT,
    full_name TEXT,
    email TEXT,
    state TEXT,
    customer_segment TEXT
);

INSERT OR REPLACE INTO _tmdl_tables VALUES ('oakhaven template', 'dim_employee', '43d7354d-c14a-4ab6-ac47-3e5506aec046');
INSERT INTO _tmdl_columns VALUES ('oakhaven template', 'dim_employee', 'employee_id', 'string', 'none', 'employee_id', 'Unique employee identification number (1..35).');
INSERT INTO _tmdl_columns VALUES ('oakhaven template', 'dim_employee', 'full_name', 'string', 'none', 'full_name', 'Concatenated customer full name (first + last).');
INSERT INTO _tmdl_columns VALUES ('oakhaven template', 'dim_employee', 'department', 'string', 'none', 'department', 'Company department (Sales, Support, Warehouse, Management).');
INSERT INTO _tmdl_columns VALUES ('oakhaven template', 'dim_employee', 'region', 'string', 'none', 'region', 'Assigned geographical sales territory (West, East, Central, South).');
CREATE TABLE IF NOT EXISTS tmdl_oakhaven_template_dim_employee (
    employee_id TEXT,
    full_name TEXT,
    department TEXT,
    region TEXT
);

INSERT OR REPLACE INTO _tmdl_tables VALUES ('oakhaven template', 'fact_sales', 'a1840420-f3ab-469d-9219-ef364479ba4c');
INSERT INTO _tmdl_columns VALUES ('oakhaven template', 'fact_sales', 'order_id', 'string', 'none', 'order_id', 'Unique sales order transaction header identifier.');
INSERT INTO _tmdl_columns VALUES ('oakhaven template', 'fact_sales', 'order_line_id', 'string', 'none', 'order_line_id', 'Line item sequence number (1..N) within an order.');
INSERT INTO _tmdl_columns VALUES ('oakhaven template', 'fact_sales', 'customer_id', 'string', 'none', 'customer_id', 'Unique sequential identifier (1..600) for each customer.');
INSERT INTO _tmdl_columns VALUES ('oakhaven template', 'fact_sales', 'product_id', 'string', 'none', 'product_id', 'Unique surrogate key (1..150) identifying each merchandise item.');
INSERT INTO _tmdl_columns VALUES ('oakhaven template', 'fact_sales', 'employee_id', 'string', 'none', 'employee_id', 'Unique employee identification number (1..35).');
INSERT INTO _tmdl_columns VALUES ('oakhaven template', 'fact_sales', 'datekey', 'string', 'none', 'datekey', 'Integer surrogate key in YYYYMMDD format for date joins.');
INSERT INTO _tmdl_columns VALUES ('oakhaven template', 'fact_sales', 'quantity', 'string', 'none', 'quantity', 'Number of units purchased in order line.');
INSERT INTO _tmdl_columns VALUES ('oakhaven template', 'fact_sales', 'unit_price', 'string', 'none', 'unit_price', 'Retail selling price per unit ($) at time of order.');
INSERT INTO _tmdl_columns VALUES ('oakhaven template', 'fact_sales', 'discount_pct', 'string', 'none', 'discount_pct', 'Percentage discount applied (0.00 to 0.30).');
INSERT INTO _tmdl_columns VALUES ('oakhaven template', 'fact_sales', 'net_amount', 'string', 'none', 'net_amount', 'Actual net revenue earned after applying discounts.');
INSERT INTO _tmdl_columns VALUES ('oakhaven template', 'fact_sales', 'payment_method', 'string', 'none', 'payment_method', 'Payment tender channel (Credit Card, PayPal, Cash, Debit Card).');
INSERT INTO _tmdl_columns VALUES ('oakhaven template', 'fact_sales', 'order_status', 'string', 'none', 'order_status', 'Current status of transaction (Completed, Processing, Canceled, Returned).');
INSERT INTO _tmdl_columns VALUES ('oakhaven template', 'fact_sales', 'channel', 'string', 'none', 'channel', 'Sales channel origination (Web, Mobile App, In-Store Retail).');
CREATE TABLE IF NOT EXISTS tmdl_oakhaven_template_fact_sales (
    order_id TEXT,
    order_line_id TEXT,
    customer_id TEXT,
    product_id TEXT,
    employee_id TEXT,
    datekey TEXT,
    quantity TEXT,
    unit_price TEXT,
    discount_pct TEXT,
    net_amount TEXT,
    payment_method TEXT,
    order_status TEXT,
    channel TEXT,
    FOREIGN KEY (customer_id) REFERENCES tmdl_oakhaven_template_dim_customer(customer_id),
    FOREIGN KEY (datekey) REFERENCES tmdl_oakhaven_template_dim_calendar(datekey),
    FOREIGN KEY (employee_id) REFERENCES tmdl_oakhaven_template_dim_employee(employee_id)
);

INSERT OR REPLACE INTO _tmdl_tables VALUES ('oakhaven template', 'flat_sales_all', '3ead40b5-967c-42a6-8b3a-70b6eed40bea');
INSERT INTO _tmdl_columns VALUES ('oakhaven template', 'flat_sales_all', 'order_id', 'string', 'none', 'order_id', 'Unique sales order transaction header identifier.');
INSERT INTO _tmdl_columns VALUES ('oakhaven template', 'flat_sales_all', 'order_line_id', 'string', 'none', 'order_line_id', 'Line item sequence number (1..N) within an order.');
INSERT INTO _tmdl_columns VALUES ('oakhaven template', 'flat_sales_all', 'order_date', 'string', 'none', 'order_date', 'Transaction date on which order was placed.');
INSERT INTO _tmdl_columns VALUES ('oakhaven template', 'flat_sales_all', 'customer_name', 'string', 'none', 'customer_name', 'Full name of the purchasing customer.');
INSERT INTO _tmdl_columns VALUES ('oakhaven template', 'flat_sales_all', 'product_name', 'string', 'none', 'product_name', 'Catalog description and product title.');
INSERT INTO _tmdl_columns VALUES ('oakhaven template', 'flat_sales_all', 'product_category', 'string', 'none', 'product_category', 'Merchandise category of the ordered item.');
INSERT INTO _tmdl_columns VALUES ('oakhaven template', 'flat_sales_all', 'quantity', 'string', 'none', 'quantity', 'Number of units purchased in order line.');
INSERT INTO _tmdl_columns VALUES ('oakhaven template', 'flat_sales_all', 'net_amount', 'string', 'none', 'net_amount', 'Actual net revenue earned after applying discounts.');
INSERT INTO _tmdl_columns VALUES ('oakhaven template', 'flat_sales_all', 'channel', 'string', 'none', 'channel', 'Sales channel origination (Web, Mobile App, In-Store Retail).');
CREATE TABLE IF NOT EXISTS tmdl_oakhaven_template_flat_sales_all (
    order_id TEXT,
    order_line_id TEXT,
    order_date TEXT,
    customer_name TEXT,
    product_name TEXT,
    product_category TEXT,
    quantity TEXT,
    net_amount TEXT,
    channel TEXT,
    FOREIGN KEY (order_date) REFERENCES tmdl_oakhaven_template_dim_calendar(date)
);

INSERT OR REPLACE INTO _tmdl_tables VALUES ('oakhaven template', 'flat_sales_completed', 'b6be6beb-29f1-48a5-81c0-625157189e89');
INSERT INTO _tmdl_columns VALUES ('oakhaven template', 'flat_sales_completed', 'order_id', 'string', 'none', 'order_id', 'Unique sales order transaction header identifier.');
INSERT INTO _tmdl_columns VALUES ('oakhaven template', 'flat_sales_completed', 'order_line_id', 'string', 'none', 'order_line_id', 'Line item sequence number (1..N) within an order.');
INSERT INTO _tmdl_columns VALUES ('oakhaven template', 'flat_sales_completed', 'order_date', 'string', 'none', 'order_date', 'Transaction date on which order was placed.');
INSERT INTO _tmdl_columns VALUES ('oakhaven template', 'flat_sales_completed', 'customer_name', 'string', 'none', 'customer_name', 'Full name of the purchasing customer.');
INSERT INTO _tmdl_columns VALUES ('oakhaven template', 'flat_sales_completed', 'product_name', 'string', 'none', 'product_name', 'Catalog description and product title.');
INSERT INTO _tmdl_columns VALUES ('oakhaven template', 'flat_sales_completed', 'product_category', 'string', 'none', 'product_category', 'Merchandise category of the ordered item.');
INSERT INTO _tmdl_columns VALUES ('oakhaven template', 'flat_sales_completed', 'quantity', 'string', 'none', 'quantity', 'Number of units purchased in order line.');
INSERT INTO _tmdl_columns VALUES ('oakhaven template', 'flat_sales_completed', 'net_amount', 'string', 'none', 'net_amount', 'Actual net revenue earned after applying discounts.');
INSERT INTO _tmdl_columns VALUES ('oakhaven template', 'flat_sales_completed', 'channel', 'string', 'none', 'channel', 'Sales channel origination (Web, Mobile App, In-Store Retail).');
CREATE TABLE IF NOT EXISTS tmdl_oakhaven_template_flat_sales_completed (
    order_id TEXT,
    order_line_id TEXT,
    order_date TEXT,
    customer_name TEXT,
    product_name TEXT,
    product_category TEXT,
    quantity TEXT,
    net_amount TEXT,
    channel TEXT,
    FOREIGN KEY (order_date) REFERENCES tmdl_oakhaven_template_dim_calendar(date)
);

INSERT OR REPLACE INTO _tmdl_tables VALUES ('oakhaven template', 'sql_dim_customer', '60157a56-9e5c-44e3-afe2-a1d8596c4810');
INSERT INTO _tmdl_columns VALUES ('oakhaven template', 'sql_dim_customer', 'sql_dim_customer', 'string', 'none', 'sql_dim_customer', 'Attribute column representing sql_dim_customer.');
CREATE TABLE IF NOT EXISTS tmdl_oakhaven_template_sql_dim_customer (
    sql_dim_customer TEXT
);

INSERT OR REPLACE INTO _tmdl_tables VALUES ('oakhaven template', 'sql_dim_date', 'e90299e8-e196-4d64-af85-6922f6c9c57b');
INSERT INTO _tmdl_columns VALUES ('oakhaven template', 'sql_dim_date', 'sql_dim_date', 'string', 'none', 'sql_dim_date', 'Attribute column representing sql_dim_date.');
CREATE TABLE IF NOT EXISTS tmdl_oakhaven_template_sql_dim_date (
    sql_dim_date TEXT
);

INSERT OR REPLACE INTO _tmdl_tables VALUES ('oakhaven template', 'sql_dim_employee', '40290057-dafc-4a1a-b105-70828199df3c');
INSERT INTO _tmdl_columns VALUES ('oakhaven template', 'sql_dim_employee', 'sql_dim_employee', 'string', 'none', 'sql_dim_employee', 'Attribute column representing sql_dim_employee.');
CREATE TABLE IF NOT EXISTS tmdl_oakhaven_template_sql_dim_employee (
    sql_dim_employee TEXT
);

INSERT OR REPLACE INTO _tmdl_tables VALUES ('oakhaven template', 'sql_dim_product', '5beec82b-4127-4513-be49-058477e6370a');
INSERT INTO _tmdl_columns VALUES ('oakhaven template', 'sql_dim_product', 'sql_dim_product', 'string', 'none', 'sql_dim_product', 'Attribute column representing sql_dim_product.');
CREATE TABLE IF NOT EXISTS tmdl_oakhaven_template_sql_dim_product (
    sql_dim_product TEXT
);

INSERT OR REPLACE INTO _tmdl_tables VALUES ('oakhaven template', 'sql_fact_sales', '3aaa36e0-22c9-499d-8643-e01165b98cf4');
INSERT INTO _tmdl_columns VALUES ('oakhaven template', 'sql_fact_sales', 'sql_fact_sales', 'string', 'none', 'sql_fact_sales', 'Attribute column representing sql_fact_sales.');
CREATE TABLE IF NOT EXISTS tmdl_oakhaven_template_sql_fact_sales (
    sql_fact_sales TEXT
);

INSERT OR REPLACE INTO _tmdl_tables VALUES ('oakhaven template', 'sql_flat_sales_all', 'efd15e42-7d83-4bca-b6a3-646d48ab884b');
INSERT INTO _tmdl_columns VALUES ('oakhaven template', 'sql_flat_sales_all', 'sql_flat_sales_all', 'string', 'none', 'sql_flat_sales_all', 'Attribute column representing sql_flat_sales_all.');
CREATE TABLE IF NOT EXISTS tmdl_oakhaven_template_sql_flat_sales_all (
    sql_flat_sales_all TEXT
);

INSERT OR REPLACE INTO _tmdl_tables VALUES ('oakhaven template', 'sql_flat_sales_completed', '7751f11b-efde-485d-9bdc-b92557dcf54d');
INSERT INTO _tmdl_columns VALUES ('oakhaven template', 'sql_flat_sales_completed', 'sql_flat_sales_completed', 'string', 'none', 'sql_flat_sales_completed', 'Attribute column representing sql_flat_sales_completed.');
CREATE TABLE IF NOT EXISTS tmdl_oakhaven_template_sql_flat_sales_completed (
    sql_flat_sales_completed TEXT
);
