#!/usr/bin/env python3
"""
scan_db_sql.py - Repository Database (.db) and SQL (.sql) Catalog Scanner

Scans the repository for all SQLite databases and SQL files, introspects schemas,
computes line counts and byte footprints, extracts descriptive headers, and outputs
structured summaries in ANSI colored terminal layout, JSON, or CSV formats.
"""

import os
import sys
import json
import csv
import sqlite3
import argparse
from pathlib import Path
from typing import Dict, List, Any, Optional

REPO_ROOT = Path(__file__).parent.parent.resolve()

# ANSI Color Codes
CYAN = "\033[1;36m"
BLUE = "\033[1;34m"
GREEN = "\033[1;32m"
YELLOW = "\033[1;33m"
MAGENTA = "\033[1;35m"
WHITE = "\033[1;37m"
BOLD = "\033[1m"
DIM = "\033[2m"
RESET = "\033[0m"


def format_size(num_bytes: int) -> str:
    """Formats bytes into human readable KB / MB string."""
    if num_bytes < 1024:
        return f"{num_bytes} B"
    elif num_bytes < 1024 * 1024:
        return f"{num_bytes / 1024:.1f} KB"
    else:
        return f"{num_bytes / (1024 * 1024):.2f} MB"


def classify_layer(rel_path: Path) -> str:
    """Categorizes a file into its architectural layer or domain."""
    path_str = str(rel_path)
    if "project/bronze" in path_str:
        return "Project: Bronze Layer (Raw Ingestion & DDL)"
    elif "project/silver" in path_str:
        return "Project: Silver Layer (Data Cleaning & Quality)"
    elif "project/gold" in path_str:
        return "Project: Gold Layer (Star Schema & Aggregations)"
    elif "portfolio/01-bronze-ingestion-patterns" in path_str:
        return "Portfolio: Bronze Ingestion Patterns"
    elif "portfolio/02-silver-cleaning-patterns" in path_str:
        return "Portfolio: Silver Cleaning Patterns"
    elif "portfolio/03-date-dimension-patterns" in path_str:
        return "Portfolio: Date Dimension Patterns"
    elif "portfolio/04-dimensional-modeling-patterns" in path_str:
        return "Portfolio: Dimensional Modeling Patterns"
    elif "portfolio/05-analytical-query-patterns" in path_str:
        return "Portfolio: Analytical Query Patterns"
    elif "portfolio/05-bi-integration" in path_str:
        return "Portfolio: BI Integration & Pushdown"
    elif "pbip/sql_queries" in path_str:
        return "PBIP: Power BI Staging Queries"
    elif "pbip" in path_str:
        return "PBIP: TMDL Catalog & Extracted Views"
    else:
        return "General SQL / Scripts"


def extract_sql_summary(file_path: Path) -> str:
    """Extracts a brief summary or title from SQL comment headers."""
    try:
        with open(file_path, "r", encoding="utf-8", errors="ignore") as f:
            raw_lines = [line.strip() for line in f.readlines()[:20]]
            
            # Clean comments
            clean_lines = []
            for line in raw_lines:
                c = line.lstrip("-/*# \t").rstrip("*/ \t")
                if not c or set(c) <= set("=-~*#"):
                    continue
                clean_lines.append(c)

            # 1. Look for explicit pattern/title comment lines
            for clean in clean_lines:
                if any(clean.lower().startswith(prefix) for prefix in ["pattern:", "problem:", "purpose:", "name:", "title:"]):
                    return clean.split(":", 1)[1].strip()
                if " - " in clean and not clean.lower().startswith("sqlite3"):
                    return clean.strip()
            
            # 2. Look for lines with colon like "silver_sales: cleaned/standardized view..."
            for clean in clean_lines:
                if ":" in clean and not clean.lower().startswith("sqlite3") and not clean.lower().startswith("generated by"):
                    return clean.strip()

            # 3. Fallback to the first non-empty descriptive comment line
            for clean in clean_lines:
                if not clean.lower().startswith("create") and not clean.lower().startswith("select") and not clean.lower().startswith("drop") and len(clean) > 5:
                    return clean.strip()
    except Exception:
        pass
    return "SQL query script"


def introspect_sqlite_db(db_path: Path) -> Dict[str, Any]:
    """Inspects a SQLite database in strict read-only mode."""
    info = {
        "tables_count": 0,
        "views_count": 0,
        "tables": [],
        "views": [],
        "total_rows": 0,
        "is_accessible": True,
        "error": None
    }
    try:
        # Strict read-only URI mode to honor AGENTS.md database immutability rules
        uri = f"file:{db_path.resolve()}?mode=ro"
        conn = sqlite3.connect(uri, uri=True)
        cursor = conn.cursor()
        
        # Get tables
        cursor.execute("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%';")
        tables = [row[0] for row in cursor.fetchall()]
        info["tables"] = tables
        info["tables_count"] = len(tables)
        
        # Get views
        cursor.execute("SELECT name FROM sqlite_master WHERE type='view';")
        views = [row[0] for row in cursor.fetchall()]
        info["views"] = views
        info["views_count"] = len(views)
        
        # Count total rows across physical tables
        total_rows = 0
        for tbl in tables:
            try:
                # Sanitize table identifier
                safe_name = tbl.replace('"', '""')
                cursor.execute(f'SELECT COUNT(*) FROM "{safe_name}";')
                total_rows += cursor.fetchone()[0]
            except Exception:
                pass
        info["total_rows"] = total_rows
        conn.close()
    except Exception as e:
        info["is_accessible"] = False
        info["error"] = str(e)
    return info


def scan_repository(repo_root: Path = REPO_ROOT) -> Dict[str, Any]:
    """Scans all .db and .sql files across the repository."""
    db_paths = sorted([p for p in repo_root.rglob("*.db") if not any(part.startswith(".") for part in p.parts if part not in [".", ".."])])
    sql_paths = sorted([p for p in repo_root.rglob("*.sql") if not any(part.startswith(".") for part in p.parts if part not in [".", ".."])])

    databases = []
    for p in db_paths:
        rel = p.relative_to(repo_root)
        size = p.stat().st_size
        db_meta = introspect_sqlite_db(p)
        databases.append({
            "path": str(rel),
            "filename": p.name,
            "size_bytes": size,
            "size_formatted": format_size(size),
            "layer": "SQLite Database",
            "tables_count": db_meta["tables_count"],
            "views_count": db_meta["views_count"],
            "tables": db_meta["tables"],
            "views": db_meta["views"],
            "total_rows": db_meta["total_rows"],
            "error": db_meta["error"]
        })

    sql_files = []
    total_sql_lines = 0
    total_sql_bytes = 0

    for p in sql_paths:
        rel = p.relative_to(repo_root)
        size = p.stat().st_size
        try:
            content = p.read_text(encoding="utf-8", errors="ignore")
            lines = len(content.splitlines())
        except Exception:
            lines = 0
        
        total_sql_lines += lines
        total_sql_bytes += size
        summary = extract_sql_summary(p)
        layer = classify_layer(rel)

        sql_files.append({
            "path": str(rel),
            "filename": p.name,
            "layer": layer,
            "lines": lines,
            "size_bytes": size,
            "size_formatted": format_size(size),
            "summary": summary
        })

    return {
        "repo_root": str(repo_root),
        "db_count": len(databases),
        "sql_count": len(sql_files),
        "total_files": len(databases) + len(sql_files),
        "total_sql_lines": total_sql_lines,
        "total_sql_bytes": total_sql_bytes,
        "total_sql_size_formatted": format_size(total_sql_bytes),
        "databases": databases,
        "sql_files": sql_files
    }


def render_terminal(data: Dict[str, Any], filter_type: str = "all", filter_layer: str = "all") -> None:
    """Renders formatted ANSI output for interactive terminal display."""
    print()
    print(f"{CYAN}╔═══════════════════════════════════════════════════════════════════════════════════════╗{RESET}")
    print(f"{CYAN}║                    ⚡ SQL PRACTICE — DATABASE & SQL CATALOG SCANNER ⚡                 ║{RESET}")
    print(f"{CYAN}╚═══════════════════════════════════════════════════════════════════════════════════════╝{RESET}")
    print(f"{DIM}Repository:{RESET} {BOLD}{data['repo_root']}{RESET}")
    print(f"{DIM}Summary:{RESET}    {GREEN}{data['db_count']} Database(s){RESET} │ {BLUE}{data['sql_count']} SQL Files{RESET} │ {YELLOW}{data['total_sql_lines']:,} Total SQL Lines{RESET} │ {MAGENTA}{data['total_sql_size_formatted']}{RESET}")
    print(f"{CYAN}─────────────────────────────────────────────────────────────────────────────────────────{RESET}")

    # 1. DATABASE FILES
    if filter_type in ["all", "db"]:
        print(f"\n{BOLD}{GREEN}📦 SQLITE DATABASE FILES (.db){RESET} ({len(data['databases'])} total)")
        print(f"{DIM}{'─' * 89}{RESET}")
        for db in data["databases"]:
            print(f" {GREEN}●{RESET} {BOLD}{db['path']}{RESET}  {DIM}({db['size_formatted']}){RESET}")
            if db["error"]:
                print(f"   {YELLOW}⚠ Access note:{RESET} {db['error']}")
            else:
                tbl_summary = f"{db['tables_count']} physical tables, {db['views_count']} views, {db['total_rows']:,} records"
                print(f"   {CYAN}Schema:{RESET} {tbl_summary}")
                if db["tables"]:
                    tbl_list = ", ".join(db["tables"][:8]) + ("..." if len(db["tables"]) > 8 else "")
                    print(f"   {DIM}Tables:{RESET} {tbl_list}")
                if db["views"]:
                    view_list = ", ".join(db["views"][:8]) + ("..." if len(db["views"]) > 8 else "")
                    print(f"   {DIM}Views :{RESET} {view_list}")
            print()

    # 2. SQL FILES GROUPED BY LAYER
    if filter_type in ["all", "sql"]:
        # Group SQL files
        groups: Dict[str, List[Dict[str, Any]]] = {}
        for sql in data["sql_files"]:
            layer = sql["layer"]
            if filter_layer != "all" and filter_layer.lower() not in layer.lower():
                continue
            groups.setdefault(layer, []).append(sql)

        print(f"\n{BOLD}{BLUE}📄 SQL SOURCE & PATTERN FILES (.sql){RESET} ({sum(len(v) for v in groups.values())} files)")
        print(f"{DIM}{'─' * 89}{RESET}")

        for layer_name, files in groups.items():
            print(f"\n{BOLD}{MAGENTA}📁 {layer_name}{RESET} {DIM}({len(files)} files){RESET}")
            for item in files:
                line_badge = f"{YELLOW}{item['lines']:>4}L{RESET}"
                size_badge = f"{DIM}{item['size_formatted']:>8}{RESET}"
                print(f"  {BLUE}➜{RESET} {BOLD}{item['path']:<46}{RESET} {line_badge} {size_badge}")
                if item["summary"]:
                    print(f"    {DIM}└─ {item['summary']}{RESET}")
        print()

    print(f"{CYAN}─────────────────────────────────────────────────────────────────────────────────────────{RESET}")
    print(f"{DIM}Quick Tips: Use --json for tooling, --csv for spreadsheets, or inspect with sqlite3 CLI.{RESET}")
    print()


def main():
    parser = argparse.ArgumentParser(description="Scan and catalog all .db and .sql files in the sql-practice repo.")
    parser.add_argument("--render", action="store_true", help="Print rich formatted ANSI output to stdout (default).")
    parser.add_argument("--json", action="store_true", help="Output catalog as structured JSON.")
    parser.add_argument("--csv", action="store_true", help="Output catalog as CSV records.")
    parser.add_argument("--type", choices=["all", "db", "sql"], default="all", help="Filter by file type (all, db, or sql).")
    parser.add_argument("--layer", default="all", help="Filter SQL files by layer/pattern keyword (e.g. bronze, silver, gold, portfolio, pbip).")

    args = parser.parse_args()
    data = scan_repository(REPO_ROOT)

    if args.json:
        print(json.dumps(data, indent=2))
        return

    if args.csv:
        writer = csv.writer(sys.stdout)
        writer.writerow(["Type", "Relative Path", "File Name", "Layer/Category", "Lines", "Size Bytes", "Size Formatted", "Summary/Schema"])
        for db in data["databases"]:
            summary = f"Tables: {db['tables_count']}, Views: {db['views_count']}, Total Rows: {db['total_rows']}"
            writer.writerow(["DB", db["path"], db["filename"], db["layer"], "", db["size_bytes"], db["size_formatted"], summary])
        for sql in data["sql_files"]:
            writer.writerow(["SQL", sql["path"], sql["filename"], sql["layer"], sql["lines"], sql["size_bytes"], sql["size_formatted"], sql["summary"]])
        return

    # Default to formatted terminal render
    render_terminal(data, filter_type=args.type, filter_layer=args.layer)


if __name__ == "__main__":
    main()
