table dim_employee
	lineageTag: 43d7354d-c14a-4ab6-ac47-3e5506aec046

	column employee_id
		dataType: int64
		formatString: 0
		lineageTag: ae9c803e-b41e-47f0-bfe5-53dc70556787
		summarizeBy: none
		sourceColumn: employee_id

		annotation SummarizationSetBy = Automatic

	column full_name
		dataType: string
		lineageTag: 5537ce32-b016-44fc-b0a7-2d262f14b77a
		summarizeBy: none
		sourceColumn: full_name

		annotation SummarizationSetBy = Automatic

	column department
		dataType: string
		lineageTag: 00fa833f-3d0f-4760-bf3a-ce4b255e9c85
		summarizeBy: none
		sourceColumn: department

		annotation SummarizationSetBy = Automatic

	column region
		dataType: string
		lineageTag: 34575c7c-a358-4f56-8c6c-32ee08e3f032
		summarizeBy: none
		sourceColumn: region

		annotation SummarizationSetBy = Automatic

	partition dim_employee = m
		mode: import
		source = ```
				let
				    // 1. Execute the Python script and inject your parameters safely with explicit Int64 types
				    Source = Python.Execute("import sqlite3#(lf)import pandas as pd#(lf)import matplotlib as mpl#(lf)#(lf)conn = sqlite3.connect(""C:\Github\sql-practice\project\oakhaven.db"")#(lf)df = pd.read_sql_query(""""""#(lf)SELECT DISTINCT #(lf)    e.employee_id,#(lf)    e.full_name,#(lf)    e.department,#(lf)    e.region#(lf)FROM dim_employee e#(lf)WHERE e.employee_id IN (#(lf)    SELECT employee_id #(lf)    FROM fact_sales #(lf)    ORDER BY order_date DESC, order_id, order_line_id #(lf)    LIMIT 100#(lf));#(lf)"""""", conn, dtype={'employee_id': 'Int64'})#(lf)conn.close()"),
				    
				    // 2. Extract the dataframe 'df' that Python generated
				    DataTable = Source{[Name="df"]}[Value],
				    
				    // 3. Transform column data types
				    #"Changed Type" = Table.TransformColumnTypes(DataTable,{
				        {"employee_id", Int64.Type},
				        {"full_name", type text},
				        {"department", type text},
				        {"region", type text}
				    })
				in
				    #"Changed Type"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

