#!/usr/bin/env python3
"""
pbip_to_db.py - TMDL to Database SQL View & DDL Compiler

Extracts embedded SQL queries from Power BI Project (.pbip) TMDL definitions,
unescapes Power Query M formatting (#(cr)#(lf), escaped quotes), and compiles
them into clean SQL CREATE VIEW statements ready to push back into a database.
"""

import os
import re
import sys
import sqlite3
import argparse
from pathlib import Path

REPO_ROOT = Path(__file__).parent.parent.parent.resolve()
PROJECTS_DIR = REPO_ROOT / "pbip" / "projects"
OUTPUT_SQL_FILE = REPO_ROOT / "pbip" / "extracted_views.sql"


def unescape_m_sql(raw_sql):
    """Unescapes Power Query M formatting codes and escaped quotes into clean ANSI SQL."""
    clean = raw_sql.replace("#(cr)#(lf)", "\n").replace("#(lf)", "\n").replace("#(cr)", "\n")
    clean = clean.replace('""', '"')
    clean = clean.replace('\\"', '"')
    clean = clean.replace("\\'", "'")
    return clean.strip()


def extract_sql_from_tmdl(tmdl_path):
    """Parses a single TMDL file to extract table name and clean embedded SQL query."""
    content = tmdl_path.read_text(encoding="utf-8", errors="replace")

    # Determine view name from TMDL table header
    table_match = re.search(r"^table\s+([^\s\n]+)", content, re.MULTILINE)
    table_name = table_match.group(1) if table_match else tmdl_path.stem

    sql_query = None

    # Pattern A: Standard M partition string literal (e.g. Source = "SELECT ...")
    m_match = re.search(r'Source\s*=\s*"(SELECT\s+.*?)"(?=\s*\n|\s*$)', content, re.IGNORECASE | re.DOTALL)
    if m_match:
        sql_query = unescape_m_sql(m_match.group(1))

    # Pattern B: Python Execute inline pandas read_sql_query
    if not sql_query:
        py_match = re.search(r'read_sql_query\(\s*(?:"""|")\s*(SELECT\s+.*?)(?:"""|")\s*,', content, re.IGNORECASE | re.DOTALL)
        if py_match:
            sql_query = unescape_m_sql(py_match.group(1))

    # Pattern C: Generic SELECT extraction fallback
    if not sql_query and "SELECT " in content.upper():
        gen_match = re.search(r'(SELECT\s+.*?;)', content, re.IGNORECASE | re.DOTALL)
        if gen_match:
            sql_query = unescape_m_sql(gen_match.group(1))

    return table_name, sql_query


def parse_all_tmdl_projects():
    """Scans all TMDL files in projects/ and compiles clean CREATE VIEW statements."""
    print("==================================================================")
    print("  PBIP TMDL TO DATABASE VIEW COMPILER (TMDL ➔ SQL Pushdown Engine)")
    print("==================================================================")
    print(f"Projects Folder : {PROJECTS_DIR}")
    print(f"Output SQL File : {OUTPUT_SQL_FILE}\n")

    if not PROJECTS_DIR.exists():
        print(f"[ERROR] Directory not found: {PROJECTS_DIR}")
        sys.exit(1)

    tmdl_files = sorted(PROJECTS_DIR.rglob("*.tmdl"))
    extracted_views = {}

    for tmdl in tmdl_files:
        table_name, sql_query = extract_sql_from_tmdl(tmdl)
        if sql_query:
            # Create unique view key based on file/folder context to prevent collisions
            project_name = tmdl.relative_to(PROJECTS_DIR).parts[0]
            view_key = f"{project_name}_{table_name}".replace(" ", "_").replace(".", "_").lower()
            
            # Clean up trailing semicolons inside view definition
            inner_sql = sql_query.rstrip(";").strip()
            
            view_statement = f"-- Source: {tmdl.relative_to(PROJECTS_DIR)}\nCREATE VIEW IF NOT EXISTS {view_key} AS\n{inner_sql};"
            extracted_views[view_key] = view_statement

    print(f"Successfully extracted {len(extracted_views)} clean SQL views from TMDL metadata.\n")

    # Write combined .sql file
    sql_header = [
        "-- =============================================================================",
        "-- AUTOMATICALLY EXTRACTED VIEWS FROM POWER BI PROJECT (.PBIP / TMDL) METADATA",
        "-- Generated by: pbip/pyscripts/pbip_to_db.py",
        "-- Purpose: Push presentation/semantic layer queries back into database views.",
        "-- =============================================================================\n\n"
    ]
    
    combined_sql = "\n\n".join(sql_header + list(extracted_views.values()))
    OUTPUT_SQL_FILE.write_text(combined_sql, encoding="utf-8")
    print(f"✅ Generated SQL View Bundle: {OUTPUT_SQL_FILE}")

    return extracted_views


def test_push_to_scratch_db(extracted_views):
    """Executes the extracted CREATE VIEW statements against a scratch SQLite database to verify syntax."""
    scratch_db = Path("/tmp/scratch_pbip_views.db")
    if scratch_db.exists():
        scratch_db.unlink()

    # Copy schema from oakhaven.db to scratch database
    source_db = REPO_ROOT / "project" / "oakhaven.db"
    if source_db.exists():
        src_conn = sqlite3.connect(source_db)
        dst_conn = sqlite3.connect(scratch_db)
        src_conn.backup(dst_conn)
        src_conn.close()
        dst_conn.close()

    conn = sqlite3.connect(scratch_db)
    cursor = conn.cursor()
    
    success_count = 0
    fail_count = 0

    print("\n------------------------------------------------------------------")
    print(f"Testing View Execution against Scratch Database ({scratch_db}):")
    print("------------------------------------------------------------------")

    for view_key, view_sql in extracted_views.items():
        try:
            cursor.executescript(view_sql)
            # Verify view can be queried
            cursor.execute(f"SELECT count(*) FROM {view_key};")
            row_count = cursor.fetchone()[0]
            print(f"  ✅ [VIEW CREATED & VERIFIED] `{view_key}` -> {row_count} rows")
            success_count += 1
        except Exception as e:
            print(f"  ❌ [ERROR CREATING VIEW] `{view_key}`: {e}")
            fail_count += 1

    conn.close()
    print("------------------------------------------------------------------")
    print(f"Execution Summary: {success_count} views successfully compiled & verified, {fail_count} failed.")
    print("------------------------------------------------------------------")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Extract SQL queries from TMDL and push to DB views")
    parser.add_argument("--test-db", action="store_true", help="Execute CREATE VIEW statements against a scratch SQLite DB to verify syntax")
    args = parser.parse_args()
    
    views = parse_all_tmdl_projects()
    if args.test_db:
        test_push_to_scratch_db(views)
